//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC1_MEM_CAP_HXX__
#define __ADC1_MEM_CAP_HXX__

#define ADC1_MEM_CAP_CAPTURE_PLAYBACK_CONTROL        (REG_ADC1_MEM_CAP+0x0)
#define ADC1_MEM_CAP_CAPTURE_PLAYBACK_STATUS         (REG_ADC1_MEM_CAP+0x4)
#define ADC1_MEM_CAP_START_CAPTURE_PLAYBACK_ADDRESS  (REG_ADC1_MEM_CAP+0x8)
#define ADC1_MEM_CAP_BYTE_WRITE_MASK                 (REG_ADC1_MEM_CAP+0xc)
#define ADC1_MEM_CAP_CEN_MASK                        (REG_ADC1_MEM_CAP+0x10)
#define ADC1_MEM_CAP_AXI_BUS_MUX_Q                   (REG_ADC1_MEM_CAP+0x14)
#define ADC1_MEM_CAP_SHARED_SRAM_CONTROL             (REG_ADC1_MEM_CAP+0x18)
#define ADC1_MEM_CAP_SRAM_15_CONTROL                 (REG_ADC1_MEM_CAP+0x1c)
#define ADC1_MEM_CAP_SRAM_14_CONTROL                 (REG_ADC1_MEM_CAP+0x20)
#define ADC1_MEM_CAP_SRAM_13_CONTROL                 (REG_ADC1_MEM_CAP+0x24)
#define ADC1_MEM_CAP_SRAM_12_CONTROL                 (REG_ADC1_MEM_CAP+0x28)
#define ADC1_MEM_CAP_SRAM_11_CONTROL                 (REG_ADC1_MEM_CAP+0x2c)
#define ADC1_MEM_CAP_SRAM_10_CONTROL                 (REG_ADC1_MEM_CAP+0x30)
#define ADC1_MEM_CAP_SRAM_9_CONTROL                  (REG_ADC1_MEM_CAP+0x34)
#define ADC1_MEM_CAP_SRAM_8_CONTROL                  (REG_ADC1_MEM_CAP+0x38)
#define ADC1_MEM_CAP_SRAM_7_CONTROL                  (REG_ADC1_MEM_CAP+0x3c)
#define ADC1_MEM_CAP_SRAM_6_CONTROL                  (REG_ADC1_MEM_CAP+0x40)
#define ADC1_MEM_CAP_SRAM_5_CONTROL                  (REG_ADC1_MEM_CAP+0x44)
#define ADC1_MEM_CAP_SRAM_4_CONTROL                  (REG_ADC1_MEM_CAP+0x48)
#define ADC1_MEM_CAP_SRAM_3_CONTROL                  (REG_ADC1_MEM_CAP+0x4c)
#define ADC1_MEM_CAP_SRAM_2_CONTROL                  (REG_ADC1_MEM_CAP+0x50)
#define ADC1_MEM_CAP_SRAM_1_CONTROL                  (REG_ADC1_MEM_CAP+0x54)
#define ADC1_MEM_CAP_SRAM_0_CONTROL                  (REG_ADC1_MEM_CAP+0x58)
#define ADC1_MEM_CAP_INITIATE_CAPTURE_CONTROL        (REG_ADC1_MEM_CAP+0x5c)
#define ADC1_MEM_CAP_INITIATE_PLAYBACK_CONTROL       (REG_ADC1_MEM_CAP+0x60)

#endif /* __ADC1_MEM_CAP_HXX__ */
