//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC1_TOP_HXX__
#define __ADC1_TOP_HXX__

#define ADC1_TOP_ADC16_PWR         (REG_ADC1_TOP+0x0)
#define ADC1_TOP_ADC16_MUX         (REG_ADC1_TOP+0x4)
#define ADC1_TOP_ADC16_CALDAC      (REG_ADC1_TOP+0x8)
#define ADC1_TOP_ADC16_DLL         (REG_ADC1_TOP+0xc)
#define ADC1_TOP_ADC16_DLL_STATUS  (REG_ADC1_TOP+0x10)
#define ADC1_TOP_ADC16_BIAS        (REG_ADC1_TOP+0x14)
#define ADC1_TOP_ADC16_LDO1        (REG_ADC1_TOP+0x18)
#define ADC1_TOP_ADC16_LDO2        (REG_ADC1_TOP+0x1c)
#define ADC1_TOP_ADC16_LDO3        (REG_ADC1_TOP+0x20)
#define ADC1_TOP_ADC16_DIGI_CLK    (REG_ADC1_TOP+0x24)
#define ADC1_TOP_ADC16_SH          (REG_ADC1_TOP+0x28)
#define ADC1_TOP_ADC16_ATEST       (REG_ADC1_TOP+0x2c)
#define ADC1_TOP_SW_CAL_CTRL       (REG_ADC1_TOP+0x30)
#define ADC1_TOP_SW_CAL_STATUS     (REG_ADC1_TOP+0x34)
#define ADC1_TOP_SYNC_STATUS       (REG_ADC1_TOP+0x38)

#endif /* __ADC1_TOP_HXX__ */
