//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC2_DSP_HXX__
#define __ADC2_DSP_HXX__

#define ADC2_DSP_GLOBAL_CONFIGURATION      (REG_ADC2_DSP+0x0)
#define ADC2_DSP_BAND1_CONFIGURATION       (REG_ADC2_DSP+0x4)
#define ADC2_DSP_BAND2_CONFIGURATION       (REG_ADC2_DSP+0x8)
#define ADC2_DSP_BAND1_FREQUENCY1          (REG_ADC2_DSP+0xc)
#define ADC2_DSP_BAND2_FREQUENCY1          (REG_ADC2_DSP+0x10)
#define ADC2_DSP_BAND1_FREQUENCY2          (REG_ADC2_DSP+0x14)
#define ADC2_DSP_BAND2_FREQUENCY2          (REG_ADC2_DSP+0x18)
#define ADC2_DSP_BAND1_FREQUENCY3          (REG_ADC2_DSP+0x1c)
#define ADC2_DSP_BAND2_FREQUENCY3          (REG_ADC2_DSP+0x20)
#define ADC2_DSP_BAND1_FREQUENCY4          (REG_ADC2_DSP+0x24)
#define ADC2_DSP_BAND2_FREQUENCY4          (REG_ADC2_DSP+0x28)
#define ADC2_DSP_BAND1_FREQUENCY5          (REG_ADC2_DSP+0x2c)
#define ADC2_DSP_BAND2_FREQUENCY5          (REG_ADC2_DSP+0x30)
#define ADC2_DSP_BAND1_FREQUENCY6          (REG_ADC2_DSP+0x34)
#define ADC2_DSP_BAND2_FREQUENCY6          (REG_ADC2_DSP+0x38)
#define ADC2_DSP_BAND1_FREQUENCY7          (REG_ADC2_DSP+0x3c)
#define ADC2_DSP_BAND2_FREQUENCY7          (REG_ADC2_DSP+0x40)
#define ADC2_DSP_BAND1_FREQUENCY8          (REG_ADC2_DSP+0x44)
#define ADC2_DSP_BAND2_FREQUENCY8          (REG_ADC2_DSP+0x48)
#define ADC2_DSP_BAND1_INITIAL_PHASE1      (REG_ADC2_DSP+0x4c)
#define ADC2_DSP_BAND2_INITIAL_PHASE1      (REG_ADC2_DSP+0x50)
#define ADC2_DSP_BAND1_INITIAL_PHASE2      (REG_ADC2_DSP+0x54)
#define ADC2_DSP_BAND2_INITIAL_PHASE2      (REG_ADC2_DSP+0x58)
#define ADC2_DSP_BAND1_INITIAL_PHASE3      (REG_ADC2_DSP+0x5c)
#define ADC2_DSP_BAND2_INITIAL_PHASE3      (REG_ADC2_DSP+0x60)
#define ADC2_DSP_BAND1_INITIAL_PHASE4      (REG_ADC2_DSP+0x64)
#define ADC2_DSP_BAND2_INITIAL_PHASE4      (REG_ADC2_DSP+0x68)
#define ADC2_DSP_BAND1_INITIAL_PHASE5      (REG_ADC2_DSP+0x6c)
#define ADC2_DSP_BAND2_INITIAL_PHASE5      (REG_ADC2_DSP+0x70)
#define ADC2_DSP_BAND1_INITIAL_PHASE6      (REG_ADC2_DSP+0x74)
#define ADC2_DSP_BAND2_INITIAL_PHASE6      (REG_ADC2_DSP+0x78)
#define ADC2_DSP_BAND1_INITIAL_PHASE7      (REG_ADC2_DSP+0x7c)
#define ADC2_DSP_BAND2_INITIAL_PHASE7      (REG_ADC2_DSP+0x80)
#define ADC2_DSP_BAND1_INITIAL_PHASE8      (REG_ADC2_DSP+0x84)
#define ADC2_DSP_BAND2_INITIAL_PHASE8      (REG_ADC2_DSP+0x88)
#define ADC2_DSP_BAND1_STATUS              (REG_ADC2_DSP+0x8c)
#define ADC2_DSP_BAND2_STATUS              (REG_ADC2_DSP+0x90)
#define ADC2_DSP_BAND1_TEST_CONFIGURATION  (REG_ADC2_DSP+0x94)
#define ADC2_DSP_BAND2_TEST_CONFIGURATION  (REG_ADC2_DSP+0x98)

#endif /* __ADC2_DSP_HXX__ */
