//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC2_CH13_HXX__
#define __ADC2_CH13_HXX__

#define ADC2_CH13_TDC_LUT00            (REG_ADC2_CH13+0x0)
#define ADC2_CH13_TDC_LUT01            (REG_ADC2_CH13+0x4)
#define ADC2_CH13_TDC_LUT02            (REG_ADC2_CH13+0x8)
#define ADC2_CH13_TDC_LUT03            (REG_ADC2_CH13+0xc)
#define ADC2_CH13_TDC_LUT04            (REG_ADC2_CH13+0x10)
#define ADC2_CH13_TDC_LUT05            (REG_ADC2_CH13+0x14)
#define ADC2_CH13_TDC_LUT06            (REG_ADC2_CH13+0x18)
#define ADC2_CH13_TDC_LUT07            (REG_ADC2_CH13+0x1c)
#define ADC2_CH13_TDC_LUT08            (REG_ADC2_CH13+0x20)
#define ADC2_CH13_TDC_BUS_ACCESS       (REG_ADC2_CH13+0x24)
#define ADC2_CH13_TDC_OFFSET_AND_GAIN  (REG_ADC2_CH13+0x28)
#define ADC2_CH13_TDC_TI_CAL           (REG_ADC2_CH13+0x2c)
#define ADC2_CH13_TDC_MISC             (REG_ADC2_CH13+0x30)
#define ADC2_CH13_TDC_CAL              (REG_ADC2_CH13+0x34)
#define ADC2_CH13_TDC_DITHER           (REG_ADC2_CH13+0x38)
#define ADC2_CH13_TDC_BIT_WEIGHTS0     (REG_ADC2_CH13+0x3c)
#define ADC2_CH13_TDC_BIT_WEIGHTS1     (REG_ADC2_CH13+0x40)
#define ADC2_CH13_TDC_STATUS           (REG_ADC2_CH13+0x44)

#endif /* __ADC2_CH13_HXX__ */
