//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC2_TI_CAL_HXX__
#define __ADC2_TI_CAL_HXX__

#define ADC2_TI_CAL_TI_CTRL1      (REG_ADC2_TI_CAL+0x0)
#define ADC2_TI_CAL_TI_CTRL2      (REG_ADC2_TI_CAL+0x4)
#define ADC2_TI_CAL_TI_TC_FORCE1  (REG_ADC2_TI_CAL+0x8)
#define ADC2_TI_CAL_TI_TC_FORCE2  (REG_ADC2_TI_CAL+0xc)
#define ADC2_TI_CAL_TI_TC_MUX     (REG_ADC2_TI_CAL+0x10)

#endif /* __ADC2_TI_CAL_HXX__ */
