//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM v3.0.1
// IQ-Analog Corp. 2013,2014,2015,2016.

#ifndef __ADC_BUS_REGS__
#define __ADC_BUS_REGS__

#ifndef __ADC_BUS_TH__
#define __ADC_BUS_TH__
#define ADC_BUS_TH(x,y) (x).adc_bus_th_register[(y)].adc_bus_th_u.data
#define ADC_BUS_DEL_CTRL(x,y) (x).adc_bus_th_register[(y)].adc_bus_th_u.bits.del_ctrl
#define ADC_BUS_FORCE_HI(x,y) (x).adc_bus_th_register[(y)].adc_bus_th_u.bits.force_hi
#define ADC_BUS_FORCE_LO(x,y) (x).adc_bus_th_register[(y)].adc_bus_th_u.bits.force_lo
typedef struct adc_bus_th_s {
	union {
		uint8_t data;
		struct {
			unsigned int del_ctrl : 6;
			unsigned int force_hi : 1;
			unsigned int force_lo : 1;
		} bits;
	} adc_bus_th_u;
  uint8_t addr;
} adc_bus_th_t;

typedef struct {
	union {
		uint8_t data;
		struct {
			unsigned int del_ctrl : 6;
			unsigned int force_hi : 1;
			unsigned int force_lo : 1;
		} bits;
	} adc_bus_th_u;
  uint8_t addr;
} __attribute__((__packed__)) adc_bus_th_packed_t;
#endif /* __ADC_BUS_TH__ */


#ifndef __ADC_BUS_CTRL16__
#define __ADC_BUS_CTRL16__
#define ADC_BUS_CTRL16(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.data
#define ADC_BUS_EN_TDC(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.bits.en_tdc
#define ADC_BUS_TDC_RES(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.bits.tdc_res
#define ADC_BUS_DELRANGE(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.bits.delrange
#define ADC_BUS_TDC_CLK_PW(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.bits.tdc_clk_pw
#define ADC_BUS_SYNC_SEL(x) (x).adc_bus_ctrl16_register.adc_bus_ctrl16_u.bits.sync_sel
typedef struct adc_bus_ctrl16_s {
	union {
		uint8_t data;
		struct {
			unsigned int en_tdc : 1;
			unsigned int tdc_res : 1;
			unsigned int delrange : 2;
			unsigned int tdc_clk_pw : 2;
			unsigned int sync_sel : 2;
		} bits;
	} adc_bus_ctrl16_u;
  uint8_t addr;
} adc_bus_ctrl16_t;

typedef struct adc_bus_ctrl16_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int en_tdc : 1;
			unsigned int tdc_res : 1;
			unsigned int delrange : 2;
			unsigned int tdc_clk_pw : 2;
			unsigned int sync_sel : 2;
		} bits;
	} adc_bus_ctrl16_u;
  uint8_t addr;
} __attribute__((__packed__)) adc_bus_ctrl16_packed_t;
#endif /* __ADC_BUS_CTRL16__ */

#ifndef __ADC_BUS_CTRL17__
#define __ADC_BUS_CTRL17__
#define ADC_BUS_CTRL17(x) (x).adc_bus_ctrl17_register.adc_bus_ctrl17_u.data
#define ADC_BUS_VTC_EN(x) (x).adc_bus_ctrl17_register.adc_bus_ctrl17_u.bits.vtc_en
#define ADC_BUS_VTC_SLOPE(x) (x).adc_bus_ctrl17_register.adc_bus_ctrl17_u.bits.vtc_slope
#define ADC_BUS_VTC_SLOPE_DSM_EN(x) (x).adc_bus_ctrl17_register.adc_bus_ctrl17_u.bits.vtc_slope_dsm_en
typedef struct adc_bus_ctrl17_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_en : 1;
			unsigned int vtc_slope : 6;
			unsigned int vtc_slope_dsm_en : 1;
		} bits;
	} adc_bus_ctrl17_u;
  uint8_t addr;
} adc_bus_ctrl17_t;

typedef struct __attribute__((packed)) adc_bus_ctrl17_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_en : 1;
			unsigned int vtc_slope : 6;
			unsigned int vtc_slope_dsm_en : 1;
		} bits;
	} adc_bus_ctrl17_u;
  uint8_t addr;
} adc_bus_ctrl17_packed_t;
#endif /* __ADC_BUS_CTRL17__ */

#ifndef __ADC_BUS_CTRL18__
#define __ADC_BUS_CTRL18__
#define ADC_BUS_CTRL18(x) (x).adc_bus_ctrl18_register.adc_bus_ctrl18_u.data
#define ADC_BUS_VTC_COMP_TH_P(x) (x).adc_bus_ctrl18_register.adc_bus_ctrl18_u.bits.vtc_comp_th_p
#define ADC_BUS_VTC_PULSE_WDTH(x) (x).adc_bus_ctrl18_register.adc_bus_ctrl18_u.bits.vtc_pulse_wdth
#define ADC_BUS_GP2(x) (x).adc_bus_ctrl18_register.adc_bus_ctrl18_u.bits.gp2
typedef struct adc_bus_ctrl18_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_comp_th_p : 5;
			unsigned int vtc_pulse_wdth : 2;
			unsigned int gp2 : 1;
		} bits;
	} adc_bus_ctrl18_u;
  uint8_t addr;
} adc_bus_ctrl18_t;

typedef struct __attribute__((packed)) adc_bus_ctrl18_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_comp_th_p : 5;
			unsigned int vtc_pulse_wdth : 2;
			unsigned int gp2 : 1;
		} bits;
	} adc_bus_ctrl18_u;
  uint8_t addr;
} adc_bus_ctrl18_packed_t;
#endif /* __ADC_BUS_CTRL18__ */

#ifndef __ADC_BUS_CTRL19__
#define __ADC_BUS_CTRL19__
#define ADC_BUS_CTRL19(x) (x).adc_bus_ctrl19_register.adc_bus_ctrl19_u.data
#define ADC_BUS_VTC_COMP_TH_N(x) (x).adc_bus_ctrl19_register.adc_bus_ctrl19_u.bits.vtc_comp_th_n
#define ADC_BUS_DIV_SEL(x) (x).adc_bus_ctrl19_register.adc_bus_ctrl19_u.bits.div_sel
#define ADC_BUS_GP3(x) (x).adc_bus_ctrl19_register.adc_bus_ctrl19_u.bits.gp3
typedef struct adc_bus_ctrl19_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_comp_th_n : 5;
			unsigned int div_sel : 2;
			unsigned int gp3 : 1;
		} bits;
	} adc_bus_ctrl19_u;
  uint8_t addr;
} adc_bus_ctrl19_t;

typedef struct __attribute__((packed)) adc_bus_ctrl19_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int vtc_comp_th_n : 5;
			unsigned int div_sel : 2;
			unsigned int gp3 : 1;
		} bits;
	} adc_bus_ctrl19_u;
  uint8_t addr;
} adc_bus_ctrl19_packed_t;
#endif /* __ADC_BUS_CTRL19__ */

#ifndef __ADC_BUS_CTRL20__
#define __ADC_BUS_CTRL20__
#define ADC_BUS_CTRL20(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.data
#define ADC_BUS_TDC_CLK_DEL(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.tdc_clk_del
#define ADC_BUS_CLK_EN_T(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_en_t
#define ADC_BUS_CLK_EN_B(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_en_b
#define ADC_BUS_CLK_EN_A(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_en_a
#define ADC_BUS_CLK_EN_P2(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_en_p2
#define ADC_BUS_CLK_EN_RST(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_en_rst
#define ADC_BUS_CLK_SEL(x) (x).adc_bus_ctrl20_register.adc_bus_ctrl20_u.bits.clk_sel
typedef struct adc_bus_ctrl20_s {
	union {
		uint8_t data;
		struct {
			unsigned int tdc_clk_del : 2;
			unsigned int clk_en_t : 1;
			unsigned int clk_en_b : 1;
			unsigned int clk_en_a : 1;
			unsigned int clk_en_p2 : 1;
			unsigned int clk_en_rst : 1;
			unsigned int clk_sel : 1;
		} bits;
	} adc_bus_ctrl20_u;
  uint8_t addr;
} adc_bus_ctrl20_t;

typedef struct __attribute__((packed)) adc_bus_ctrl20_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int tdc_clk_del : 2;
			unsigned int clk_en_t : 1;
			unsigned int clk_en_b : 1;
			unsigned int clk_en_a : 1;
			unsigned int clk_en_p2 : 1;
			unsigned int clk_en_rst : 1;
			unsigned int clk_sel : 1;
		} bits;
	} adc_bus_ctrl20_u;
  uint8_t addr;
} adc_bus_ctrl20_packed_t;
#endif /* __ADC_BUS_CTRL20__ */

#ifndef __ADC_BUS_CTRL21__
#define __ADC_BUS_CTRL21__
#define ADC_BUS_CTRL21(x) (x).adc_bus_ctrl21_register.adc_bus_ctrl21_u.data
#define ADC_BUS_FORCE(x) (x).adc_bus_ctrl21_register.adc_bus_ctrl21_u.bits.force
#define ADC_BUS_GP5(x) (x).adc_bus_ctrl21_register.adc_bus_ctrl21_u.bits.gp5
typedef struct adc_bus_ctrl21_s {
	union {
		uint8_t data;
		struct {
			unsigned int force : 6;
			unsigned int gp5 : 2;
		} bits;
	} adc_bus_ctrl21_u;
  uint8_t addr;
} adc_bus_ctrl21_t;

typedef struct __attribute__((packed)) adc_bus_ctrl21_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int force : 6;
			unsigned int gp5 : 2;
		} bits;
	} adc_bus_ctrl21_u;
  uint8_t addr;
} adc_bus_ctrl21_packed_t;
#endif /* __ADC_BUS_CTRL21__ */

#ifndef __ADC_BUS_CTRL22__
#define __ADC_BUS_CTRL22__
#define ADC_BUS_CTRL22(x) (x).adc_bus_ctrl22_register.adc_bus_ctrl22_u.data
#define ADC_BUS_FORCE_VAL0(x) (x).adc_bus_ctrl22_register.adc_bus_ctrl22_u.bits.force_val0
#define ADC_BUS_FORCE_VAL1(x) (x).adc_bus_ctrl22_register.adc_bus_ctrl22_u.bits.force_val1
#define ADC_BUS_FORCE_VAL2(x) (x).adc_bus_ctrl22_register.adc_bus_ctrl22_u.bits.force_val2
#define ADC_BUS_FORCE_VAL3(x) (x).adc_bus_ctrl22_register.adc_bus_ctrl22_u.bits.force_val3
typedef struct adc_bus_ctrl22_s {
	union {
		uint8_t data;
		struct {
			unsigned int force_val0 : 2;
			unsigned int force_val1 : 2;
			unsigned int force_val2 : 2;
			unsigned int force_val3 : 2;
		} bits;
	} adc_bus_ctrl22_u;
  uint8_t addr;
} adc_bus_ctrl22_t;

typedef struct __attribute__((packed)) adc_bus_ctrl22_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int force_val0 : 2;
			unsigned int force_val1 : 2;
			unsigned int force_val2 : 2;
			unsigned int force_val3 : 2;
		} bits;
	} adc_bus_ctrl22_u;
  uint8_t addr;
} adc_bus_ctrl22_packed_t;
#endif /* __ADC_BUS_CTRL22__ */

#ifndef __ADC_BUS_CTRL23__
#define __ADC_BUS_CTRL23__
#define ADC_BUS_CTRL23(x) (x).adc_bus_ctrl23_register.adc_bus_ctrl23_u.data
#define ADC_BUS_FORCE_VAL4(x) (x).adc_bus_ctrl23_register.adc_bus_ctrl23_u.bits.force_val4
#define ADC_BUS_FORCE_VAL5(x) (x).adc_bus_ctrl23_register.adc_bus_ctrl23_u.bits.force_val5
#define ADC_BUS_GP6(x) (x).adc_bus_ctrl23_register.adc_bus_ctrl23_u.bits.gp6
typedef struct adc_bus_ctrl23_s {
	union {
		uint8_t data;
		struct {
			unsigned int force_val4 : 2;
			unsigned int force_val5 : 2;
			unsigned int gp6 : 4;
		} bits;
	} adc_bus_ctrl23_u;
  uint8_t addr;
} adc_bus_ctrl23_t;

typedef struct __attribute__((packed)) adc_bus_ctrl23_packed_s {
	union {
		uint8_t data;
		struct {
			unsigned int force_val4 : 2;
			unsigned int force_val5 : 2;
			unsigned int gp6 : 4;
		} bits;
	} adc_bus_ctrl23_u;
  uint8_t addr;
} adc_bus_ctrl23_packed_t;
#endif /* __ADC_BUS_CTRL23__ */


typedef struct adc_bus_regs_s
{
  adc_bus_th_t adc_bus_th_register[9];	// Address: 0x0 - 0x8
	adc_bus_ctrl16_t adc_bus_ctrl16_register;	// Address: 0x10
	adc_bus_ctrl17_t adc_bus_ctrl17_register;	// Address: 0x11
	adc_bus_ctrl18_t adc_bus_ctrl18_register;	// Address: 0x12
	adc_bus_ctrl19_t adc_bus_ctrl19_register;	// Address: 0x13
	adc_bus_ctrl20_t adc_bus_ctrl20_register;	// Address: 0x1c
	adc_bus_ctrl21_t adc_bus_ctrl21_register;	// Address: 0x1d
	adc_bus_ctrl22_t adc_bus_ctrl22_register;	// Address: 0x1e
	adc_bus_ctrl23_t adc_bus_ctrl23_register;	// Address: 0x1f
}  adc_bus_regs_t;

typedef struct __attribute__((packed)) adc_bus_regs_packed_s
{
   adc_bus_th_packed_t adc_bus_th_register[9];	// Address: 0x0 - 0x8
	adc_bus_ctrl16_packed_t adc_bus_ctrl16_register;	// Address: 0x10
	adc_bus_ctrl17_packed_t adc_bus_ctrl17_register;	// Address: 0x11
	adc_bus_ctrl18_packed_t adc_bus_ctrl18_register;	// Address: 0x12
	adc_bus_ctrl19_packed_t adc_bus_ctrl19_register;	// Address: 0x13
	adc_bus_ctrl20_packed_t adc_bus_ctrl20_register;	// Address: 0x1c
	adc_bus_ctrl21_packed_t adc_bus_ctrl21_register;	// Address: 0x1d
	adc_bus_ctrl22_packed_t adc_bus_ctrl22_register;	// Address: 0x1e
	adc_bus_ctrl23_packed_t adc_bus_ctrl23_register;	// Address: 0x1f
} adc_bus_regs_packed_t;



#define ADC_BUS_MISC_REG 16
#define ADC_BUS_VTC1_REG 17
#define ADC_BUS_VTC2_REG 18
#define ADC_BUS_MISC2_REG 19
#define ADC_BUS_CLK_REG 28
#define ADC_BUS_FORCE_EN_REG 29
#define ADC_BUS_FORCE1_REG 30
#define ADC_BUS_FORCE2_REG 31
#define ALL_REGS 27 // unused register id used by software 

#define ADC_BUS_DEFAULTS {{\
{{0x1c},0x0},\
{{0x1b},0x1},\
{{0x0c},0x2},\
{{0x20},0x3},\
{{0x1b},0x4},\
{{0x14},0x5},\
{{0x2c},0x6},\
{{0x28},0x7},\
{{0x24},0x8}\
},\
{{0x81},0x10},\
{{0x01},0x11},\
{{0x28},0x12},\
{{0x48},0x13},\
{{0x70},0x1c},\
{{0x00},0x1d},\
{{0x00},0x1e},\
{{0x00},0x1f}}


#endif /* __ADC_BUS_REGS__ */
