//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __ADC_DATA_CTRL_HXX__
#define __ADC_DATA_CTRL_HXX__

#define ADC_DATA_CTRL_LANE0_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x0)
#define ADC_DATA_CTRL_LANE1_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x4)
#define ADC_DATA_CTRL_LANE2_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x8)
#define ADC_DATA_CTRL_LANE3_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0xc)
#define ADC_DATA_CTRL_LANE4_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x10)
#define ADC_DATA_CTRL_LANE5_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x14)
#define ADC_DATA_CTRL_LANE6_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x18)
#define ADC_DATA_CTRL_LANE7_FANOUT_ENABLE  (REG_ADC_DATA_CTRL+0x1c)
#define ADC_DATA_CTRL_IQ_POSITION_CONTROL  (REG_ADC_DATA_CTRL+0x20)
#define ADC_DATA_CTRL_TEST_MODE_1          (REG_ADC_DATA_CTRL+0x24)

#endif /* __ADC_DATA_CTRL_HXX__ */
