//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __DAC1_POLAR_CTRL_HXX__
#define __DAC1_POLAR_CTRL_HXX__

#define DAC1_POLAR_CTRL_band0_iq_coeff0  (REG_DAC1_POLAR_CTRL+0x0)
#define DAC1_POLAR_CTRL_band0_iq_coeff1  (REG_DAC1_POLAR_CTRL+0x4)
#define DAC1_POLAR_CTRL_band0_iq_coeff2  (REG_DAC1_POLAR_CTRL+0x8)
#define DAC1_POLAR_CTRL_band0_iq_coeff3  (REG_DAC1_POLAR_CTRL+0xc)
#define DAC1_POLAR_CTRL_band0_iq_coeff4  (REG_DAC1_POLAR_CTRL+0x10)
#define DAC1_POLAR_CTRL_band0_iq_coeff5  (REG_DAC1_POLAR_CTRL+0x14)
#define DAC1_POLAR_CTRL_band0_iq_coeff6  (REG_DAC1_POLAR_CTRL+0x18)
#define DAC1_POLAR_CTRL_band0_iq_coeff7  (REG_DAC1_POLAR_CTRL+0x1c)
#define DAC1_POLAR_CTRL_band1_iq_coeff0  (REG_DAC1_POLAR_CTRL+0x20)
#define DAC1_POLAR_CTRL_band1_iq_coeff1  (REG_DAC1_POLAR_CTRL+0x24)
#define DAC1_POLAR_CTRL_band1_iq_coeff2  (REG_DAC1_POLAR_CTRL+0x28)
#define DAC1_POLAR_CTRL_band1_iq_coeff3  (REG_DAC1_POLAR_CTRL+0x2c)
#define DAC1_POLAR_CTRL_band1_iq_coeff4  (REG_DAC1_POLAR_CTRL+0x30)
#define DAC1_POLAR_CTRL_band1_iq_coeff5  (REG_DAC1_POLAR_CTRL+0x34)
#define DAC1_POLAR_CTRL_band1_iq_coeff6  (REG_DAC1_POLAR_CTRL+0x38)
#define DAC1_POLAR_CTRL_band1_iq_coeff7  (REG_DAC1_POLAR_CTRL+0x3c)

#endif /* __DAC1_POLAR_CTRL_HXX__ */
