//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __DAC1_DSP_HXX__
#define __DAC1_DSP_HXX__

#define DAC1_DSP_GLOBAL_CONFIGURATION              (REG_DAC1_DSP+0x0)
#define DAC1_DSP_BAND1_CONFIGURATION               (REG_DAC1_DSP+0x4)
#define DAC1_DSP_BAND2_CONFIGURATION               (REG_DAC1_DSP+0x8)
#define DAC1_DSP_GLOBAL_SEED_CONFIGURATION         (REG_DAC1_DSP+0xc)
#define DAC1_DSP_BAND1_FILTER_SEED_CONFIGURATION1  (REG_DAC1_DSP+0x10)
#define DAC1_DSP_BAND2_FILTER_SEED_CONFIGURATION1  (REG_DAC1_DSP+0x14)
#define DAC1_DSP_BAND1_FILTER_SEED_CONFIGURATION2  (REG_DAC1_DSP+0x18)
#define DAC1_DSP_BAND2_FILTER_SEED_CONFIGURATION2  (REG_DAC1_DSP+0x1c)
#define DAC1_DSP_BAND1_FREQUENCY1                  (REG_DAC1_DSP+0x20)
#define DAC1_DSP_BAND2_FREQUENCY1                  (REG_DAC1_DSP+0x24)
#define DAC1_DSP_BAND1_FREQUENCY2                  (REG_DAC1_DSP+0x28)
#define DAC1_DSP_BAND2_FREQUENCY2                  (REG_DAC1_DSP+0x2c)
#define DAC1_DSP_BAND1_FREQUENCY3                  (REG_DAC1_DSP+0x30)
#define DAC1_DSP_BAND2_FREQUENCY3                  (REG_DAC1_DSP+0x34)
#define DAC1_DSP_BAND1_FREQUENCY4                  (REG_DAC1_DSP+0x38)
#define DAC1_DSP_BAND2_FREQUENCY4                  (REG_DAC1_DSP+0x3c)
#define DAC1_DSP_BAND1_FREQUENCY5                  (REG_DAC1_DSP+0x40)
#define DAC1_DSP_BAND2_FREQUENCY5                  (REG_DAC1_DSP+0x44)
#define DAC1_DSP_BAND1_FREQUENCY6                  (REG_DAC1_DSP+0x48)
#define DAC1_DSP_BAND2_FREQUENCY6                  (REG_DAC1_DSP+0x4c)
#define DAC1_DSP_BAND1_FREQUENCY7                  (REG_DAC1_DSP+0x50)
#define DAC1_DSP_BAND2_FREQUENCY7                  (REG_DAC1_DSP+0x54)
#define DAC1_DSP_BAND1_FREQUENCY8                  (REG_DAC1_DSP+0x58)
#define DAC1_DSP_BAND2_FREQUENCY8                  (REG_DAC1_DSP+0x5c)
#define DAC1_DSP_BAND1_INITIAL_PHASE1              (REG_DAC1_DSP+0x60)
#define DAC1_DSP_BAND2_INITIAL_PHASE1              (REG_DAC1_DSP+0x64)
#define DAC1_DSP_BAND1_INITIAL_PHASE2              (REG_DAC1_DSP+0x68)
#define DAC1_DSP_BAND2_INITIAL_PHASE2              (REG_DAC1_DSP+0x6c)
#define DAC1_DSP_BAND1_INITIAL_PHASE3              (REG_DAC1_DSP+0x70)
#define DAC1_DSP_BAND2_INITIAL_PHASE3              (REG_DAC1_DSP+0x74)
#define DAC1_DSP_BAND1_INITIAL_PHASE4              (REG_DAC1_DSP+0x78)
#define DAC1_DSP_BAND2_INITIAL_PHASE4              (REG_DAC1_DSP+0x7c)
#define DAC1_DSP_BAND1_INITIAL_PHASE5              (REG_DAC1_DSP+0x80)
#define DAC1_DSP_BAND2_INITIAL_PHASE5              (REG_DAC1_DSP+0x84)
#define DAC1_DSP_BAND1_INITIAL_PHASE6              (REG_DAC1_DSP+0x88)
#define DAC1_DSP_BAND2_INITIAL_PHASE6              (REG_DAC1_DSP+0x8c)
#define DAC1_DSP_BAND1_INITIAL_PHASE7              (REG_DAC1_DSP+0x90)
#define DAC1_DSP_BAND2_INITIAL_PHASE7              (REG_DAC1_DSP+0x94)
#define DAC1_DSP_BAND1_INITIAL_PHASE8              (REG_DAC1_DSP+0x98)
#define DAC1_DSP_BAND2_INITIAL_PHASE8              (REG_DAC1_DSP+0x9c)
#define DAC1_DSP_BAND1_STATUS                      (REG_DAC1_DSP+0xa0)
#define DAC1_DSP_BAND2_STATUS                      (REG_DAC1_DSP+0xa4)
#define DAC1_DSP_BAND1_TEST_CONFIGURATION          (REG_DAC1_DSP+0xa8)
#define DAC1_DSP_BAND2_TEST_CONFIGURATION          (REG_DAC1_DSP+0xac)

#endif /* __DAC1_DSP_HXX__ */
