//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __DAC2_DIG_HXX__
#define __DAC2_DIG_HXX__

#define DAC2_DIG_DAC_INIT     (REG_DAC2_DIG+0x0)
#define DAC2_DIG_SYSREF_CTRL  (REG_DAC2_DIG+0x4)
#define DAC2_DIG_DEM_CTRL     (REG_DAC2_DIG+0x8)
#define DAC2_DIG_LFSR_CTRL    (REG_DAC2_DIG+0xc)
#define DAC2_DIG_ATEST_CTRL   (REG_DAC2_DIG+0x3c)
#define DAC2_DIG_PWR_CTRL     (REG_DAC2_DIG+0x40)
#define DAC2_DIG_MUX_CTRL     (REG_DAC2_DIG+0x44)
#define DAC2_DIG_DATA_CTRL    (REG_DAC2_DIG+0x48)
#define DAC2_DIG_CLK_CTRL0    (REG_DAC2_DIG+0x4c)
#define DAC2_DIG_CLK_CTRL1    (REG_DAC2_DIG+0x50)
#define DAC2_DIG_CLK_CTRL2    (REG_DAC2_DIG+0x54)
#define DAC2_DIG_CLK_CTRL3    (REG_DAC2_DIG+0x58)
#define DAC2_DIG_LDO0_CTRL    (REG_DAC2_DIG+0x5c)
#define DAC2_DIG_LDO1_CTRL    (REG_DAC2_DIG+0x60)
#define DAC2_DIG_DLL_CTRL     (REG_DAC2_DIG+0x64)
#define DAC2_DIG_TC_CTRL0     (REG_DAC2_DIG+0x68)
#define DAC2_DIG_TC_CTRL1     (REG_DAC2_DIG+0x6c)
#define DAC2_DIG_DLL_STATUS   (REG_DAC2_DIG+0x70)
#define DAC2_DIG_DAC0_GP      (REG_DAC2_DIG+0x74)
#define DAC2_DIG_DAC1_GP      (REG_DAC2_DIG+0x78)
#define DAC2_DIG_SYSREF_RD    (REG_DAC2_DIG+0x7c)

#endif /* __DAC2_DIG_HXX__ */
