//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __DAC2_MEM_PLAY_HXX__
#define __DAC2_MEM_PLAY_HXX__

#define DAC2_MEM_PLAY_CAPTURE_PLAYBACK_CONTROL        (REG_DAC2_MEM_PLAY+0x0)
#define DAC2_MEM_PLAY_CAPTURE_PLAYBACK_STATUS         (REG_DAC2_MEM_PLAY+0x4)
#define DAC2_MEM_PLAY_START_CAPTURE_PLAYBACK_ADDRESS  (REG_DAC2_MEM_PLAY+0x8)
#define DAC2_MEM_PLAY_BYTE_WRITE_MASK                 (REG_DAC2_MEM_PLAY+0xc)
#define DAC2_MEM_PLAY_CEN_MASK                        (REG_DAC2_MEM_PLAY+0x10)
#define DAC2_MEM_PLAY_AXI_BUS_MUX_Q                   (REG_DAC2_MEM_PLAY+0x14)
#define DAC2_MEM_PLAY_SHARED_SRAM_CONTROL             (REG_DAC2_MEM_PLAY+0x18)
#define DAC2_MEM_PLAY_SRAM_15_CONTROL                 (REG_DAC2_MEM_PLAY+0x1c)
#define DAC2_MEM_PLAY_SRAM_14_CONTROL                 (REG_DAC2_MEM_PLAY+0x20)
#define DAC2_MEM_PLAY_SRAM_13_CONTROL                 (REG_DAC2_MEM_PLAY+0x24)
#define DAC2_MEM_PLAY_SRAM_12_CONTROL                 (REG_DAC2_MEM_PLAY+0x28)
#define DAC2_MEM_PLAY_SRAM_11_CONTROL                 (REG_DAC2_MEM_PLAY+0x2c)
#define DAC2_MEM_PLAY_SRAM_10_CONTROL                 (REG_DAC2_MEM_PLAY+0x30)
#define DAC2_MEM_PLAY_SRAM_9_CONTROL                  (REG_DAC2_MEM_PLAY+0x34)
#define DAC2_MEM_PLAY_SRAM_8_CONTROL                  (REG_DAC2_MEM_PLAY+0x38)
#define DAC2_MEM_PLAY_SRAM_7_CONTROL                  (REG_DAC2_MEM_PLAY+0x3c)
#define DAC2_MEM_PLAY_SRAM_6_CONTROL                  (REG_DAC2_MEM_PLAY+0x40)
#define DAC2_MEM_PLAY_SRAM_5_CONTROL                  (REG_DAC2_MEM_PLAY+0x44)
#define DAC2_MEM_PLAY_SRAM_4_CONTROL                  (REG_DAC2_MEM_PLAY+0x48)
#define DAC2_MEM_PLAY_SRAM_3_CONTROL                  (REG_DAC2_MEM_PLAY+0x4c)
#define DAC2_MEM_PLAY_SRAM_2_CONTROL                  (REG_DAC2_MEM_PLAY+0x50)
#define DAC2_MEM_PLAY_SRAM_1_CONTROL                  (REG_DAC2_MEM_PLAY+0x54)
#define DAC2_MEM_PLAY_SRAM_0_CONTROL                  (REG_DAC2_MEM_PLAY+0x58)
#define DAC2_MEM_PLAY_INITIATE_CAPTURE_CONTROL        (REG_DAC2_MEM_PLAY+0x5c)
#define DAC2_MEM_PLAY_INITIATE_PLAYBACK_CONTROL       (REG_DAC2_MEM_PLAY+0x60)

#endif /* __DAC2_MEM_PLAY_HXX__ */
