//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __EP_B_HXX__
#define __EP_B_HXX__

#define EP_B_CHIP_ID          (REG_EP_B+0x0)
#define EP_B_CONFIGURATION    (REG_EP_B+0x4)
#define EP_B_AD_DELAY_SELECT  (REG_EP_B+0x8)
#define EP_B_OOPS_EPA         (REG_EP_B+0xc)
#define EP_B_OOPS_EPB         (REG_EP_B+0x10)
#define EP_B_DUMMY_BITS       (REG_EP_B+0x14)

#endif /* __EP_B_HXX__ */
