//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

#ifndef __F1000_HXX__
#define __F1000_HXX__

#include "f1000_base.hxx"

#include "FPGA.hxx"
#include "EP_A.hxx"
#include "ADC_DATA_CTRL.hxx"
#include "ADC1_MEM_CAP.hxx"
#include "ADC2_MEM_CAP.hxx"
#include "DAC1_MEM_PLAY.hxx"
#include "DAC2_MEM_PLAY.hxx"
#include "ADC1_DSP.hxx"
#include "ADC2_DSP.hxx"
#include "DAC1_DSP.hxx"
#include "DAC2_DSP.hxx"
#include "RX_LL_CORE.hxx"
#include "RX_CDR.hxx"
#include "RX_ETB.hxx"
#include "RX_LL_LANE0.hxx"
#include "RX_MERLIN_CTRL0.hxx"
#include "RX_FRAMER0.hxx"
#include "RX_LL_LANE1.hxx"
#include "RX_MERLIN_CTRL1.hxx"
#include "RX_FRAMER1.hxx"
#include "RX_LL_LANE2.hxx"
#include "RX_MERLIN_CTRL2.hxx"
#include "RX_FRAMER2.hxx"
#include "RX_LL_LANE3.hxx"
#include "RX_MERLIN_CTRL3.hxx"
#include "RX_FRAMER3.hxx"
#include "RX_LL_LANE4.hxx"
#include "RX_MERLIN_CTRL4.hxx"
#include "RX_FRAMER4.hxx"
#include "RX_LL_LANE5.hxx"
#include "RX_MERLIN_CTRL5.hxx"
#include "RX_FRAMER5.hxx"
#include "RX_LL_LANE6.hxx"
#include "RX_MERLIN_CTRL6.hxx"
#include "RX_FRAMER6.hxx"
#include "RX_LL_LANE7.hxx"
#include "RX_MERLIN_CTRL7.hxx"
#include "RX_FRAMER7.hxx"
#include "RISCV_UART.hxx"
#include "TX_LL_CORE.hxx"
#include "TX_SAT.hxx"
#include "TX_ETB.hxx"
#include "TX_DRV.hxx"
#include "TX_LL_LANE0.hxx"
#include "TX_MERLIN_CTRL0.hxx"
#include "TX_FRAMER0.hxx"
#include "TX_LL_LANE1.hxx"
#include "TX_MERLIN_CTRL1.hxx"
#include "TX_FRAMER1.hxx"
#include "TX_LL_LANE2.hxx"
#include "TX_MERLIN_CTRL2.hxx"
#include "TX_FRAMER2.hxx"
#include "TX_LL_LANE3.hxx"
#include "TX_MERLIN_CTRL3.hxx"
#include "TX_FRAMER3.hxx"
#include "TX_LL_LANE4.hxx"
#include "TX_MERLIN_CTRL4.hxx"
#include "TX_FRAMER4.hxx"
#include "TX_LL_LANE5.hxx"
#include "TX_MERLIN_CTRL5.hxx"
#include "TX_FRAMER5.hxx"
#include "TX_LL_LANE6.hxx"
#include "TX_MERLIN_CTRL6.hxx"
#include "TX_FRAMER6.hxx"
#include "TX_LL_LANE7.hxx"
#include "TX_MERLIN_CTRL7.hxx"
#include "TX_FRAMER7.hxx"
#include "TEST_DSP1_MEM_CAP.hxx"
#include "TEST_DSP2_MEM_CAP.hxx"
#include "TEST_DSP1_MEM_PLAY.hxx"
#include "TEST_DSP2_MEM_PLAY.hxx"
#include "ADC1_POLAR_CTRL.hxx"
#include "DAC1_POLAR_CTRL.hxx"
#include "ADC2_POLAR_CTRL.hxx"
#include "DAC2_POLAR_CTRL.hxx"
#include "GP.hxx"
#include "RAM_PARAM.hxx"
#include "PAD_CTRL.hxx"
#include "OOB_PROC.hxx"
#include "OOB_MERLIN.hxx"
#include "OOB_ETB.hxx"
#include "OOB_AXIFACE.hxx"
#include "ADC1_CH0.hxx"
#include "ADC1_CH1.hxx"
#include "ADC1_CH2.hxx"
#include "ADC1_CH3.hxx"
#include "ADC1_CH4.hxx"
#include "ADC1_CH5.hxx"
#include "ADC1_CH6.hxx"
#include "ADC1_CH7.hxx"
#include "ADC1_CH8.hxx"
#include "ADC1_CH9.hxx"
#include "ADC1_CH10.hxx"
#include "ADC1_CH11.hxx"
#include "ADC1_CH12.hxx"
#include "ADC1_CH13.hxx"
#include "ADC1_CH14.hxx"
#include "ADC1_CH15.hxx"
#include "ADC1_CH16.hxx"
#include "ADC1_CH17.hxx"
#include "ADC1_TI_CAL.hxx"
#include "ADC1_TOP.hxx"
#include "ADC2_CH0.hxx"
#include "ADC2_CH1.hxx"
#include "ADC2_CH2.hxx"
#include "ADC2_CH3.hxx"
#include "ADC2_CH4.hxx"
#include "ADC2_CH5.hxx"
#include "ADC2_CH6.hxx"
#include "ADC2_CH7.hxx"
#include "ADC2_CH8.hxx"
#include "ADC2_CH9.hxx"
#include "ADC2_CH10.hxx"
#include "ADC2_CH11.hxx"
#include "ADC2_CH12.hxx"
#include "ADC2_CH13.hxx"
#include "ADC2_CH14.hxx"
#include "ADC2_CH15.hxx"
#include "ADC2_CH16.hxx"
#include "ADC2_CH17.hxx"
#include "ADC2_TI_CAL.hxx"
#include "ADC2_TOP.hxx"
#include "DAC1_DIG.hxx"
#include "DAC2_DIG.hxx"
#include "EP_B.hxx"

#include "f1000_regs.hxx"

#endif /* __F1000_HXX__ */
