//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __FPGA_HXX__
#define __FPGA_HXX__

#define FPGA_EVM_ID          (REG_FPGA+0x0)
#define FPGA_EVM_REV         (REG_FPGA+0x4)
#define FPGA_EP_SELECT       (REG_FPGA+0x8)
#define FPGA_I2C_DEV_ADDR    (REG_FPGA+0x40)
#define FPGA_I2C_WR_CONTROL  (REG_FPGA+0x44)
#define FPGA_I2C_RD_CONTROL  (REG_FPGA+0x48)
#define FPGA_I2C_CMD         (REG_FPGA+0x4c)
#define FPGA_I2C_STATUS      (REG_FPGA+0x50)
#define FPGA_I2C_WR_DATA_1   (REG_FPGA+0x80)
#define FPGA_I2C_WR_DATA_2   (REG_FPGA+0x84)
#define FPGA_I2C_WR_DATA_3   (REG_FPGA+0x88)
#define FPGA_I2C_WR_DATA_4   (REG_FPGA+0x8c)
#define FPGA_I2C_WR_DATA_5   (REG_FPGA+0x90)
#define FPGA_I2C_WR_DATA_6   (REG_FPGA+0x94)
#define FPGA_I2C_WR_DATA_7   (REG_FPGA+0x98)
#define FPGA_I2C_RD_DATA_1   (REG_FPGA+0xc0)
#define FPGA_I2C_RD_DATA_2   (REG_FPGA+0xc4)
#define FPGA_I2C_RD_DATA_3   (REG_FPGA+0xc8)
#define FPGA_I2C_RD_DATA_4   (REG_FPGA+0xcc)
#define FPGA_I2C_RD_DATA_5   (REG_FPGA+0xd0)
#define FPGA_I2C_RD_DATA_6   (REG_FPGA+0xd4)
#define FPGA_I2C_RD_DATA_7   (REG_FPGA+0xd8)

#endif /* __FPGA_HXX__ */
