//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __GP_HXX__
#define __GP_HXX__

#define GP_EXT_ADC_CAL_CTRL        (REG_GP+0x0)
#define GP_EXT_ADC_RUN_CTRL        (REG_GP+0x4)
#define GP_OOPS3                   (REG_GP+0x8)
#define GP_OOPS4                   (REG_GP+0xc)
#define GP_OOPS5                   (REG_GP+0x10)
#define GP_TIMER_CONTROL_ATTEN     (REG_GP+0x14)
#define GP_ATTEN                   (REG_GP+0x18)
#define GP_RX_TX_GP                (REG_GP+0x1c)
#define GP_FORCE_FRAME_SYNC        (REG_GP+0x20)
#define GP_ADC_DAC_LOOPBACK_EN     (REG_GP+0x24)
#define GP_ATTEN_DRIVER_CTRL       (REG_GP+0x28)
#define GP_MEM_CAP_TRIGGER1        (REG_GP+0x2c)
#define GP_MEM_CAP_TRIGGER2        (REG_GP+0x30)
#define GP_TEST_MEM_CAP_TRIGGER1   (REG_GP+0x34)
#define GP_TEST_MEM_CAP_TRIGGER2   (REG_GP+0x38)
#define GP_DAC_COMP_MULT_DUMMY     (REG_GP+0x3c)
#define GP_OUT_DATA_DUMMY5         (REG_GP+0x40)
#define GP_OUT_DATA_DUMMY6         (REG_GP+0x44)
#define GP_OUT_DATA_DUMMY7         (REG_GP+0x48)
#define GP_OUT_DATA_DUMMY8         (REG_GP+0x4c)
#define GP_OUT_DATA_DUMMY9         (REG_GP+0x50)
#define GP_OUT_DATA_DUMMY10        (REG_GP+0x54)
#define GP_OUT_DATA_DUMMY11        (REG_GP+0x58)
#define GP_OUT_DATA_DUMMY12        (REG_GP+0x5c)
#define GP_OUT_DATA_DUMMY13        (REG_GP+0x60)
#define GP_OUT_DATA_DUMMY14        (REG_GP+0x64)
#define GP_OUT_DATA_DUMMY15        (REG_GP+0x68)
#define GP_OUT_DATA_DUMMY16        (REG_GP+0x6c)
#define GP_OUT_DATA_DUMMY17        (REG_GP+0x70)
#define GP_CORE_DUMMY              (REG_GP+0x74)
#define GP_MEM_PLAY_TRIGGER1       (REG_GP+0x78)
#define GP_MEM_PLAY_TRIGGER2       (REG_GP+0x7c)
#define GP_TEST_MEM_PLAY_TRIGGER1  (REG_GP+0x80)
#define GP_TEST_MEM_PLAY_TRIGGER2  (REG_GP+0x84)
#define GP_LMFC_IRQ_CONTROL        (REG_GP+0x88)
#define GP_LMFC_COUNTER            (REG_GP+0x8c)
#define GP_LMFC_IRQ_ACK            (REG_GP+0x90)
#define GP_OOB_TO_GC               (REG_GP+0x94)
#define GP_OOB_IRQ_ACK             (REG_GP+0x98)
#define GP_GC_TO_OOB               (REG_GP+0x9c)

#endif /* __GP_HXX__ */
