//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM v3.1.4
// IQ-Analog Corp. 2013-2018.

#ifndef __IMOLA_SAT_CTRL_REGS__
#define __IMOLA_SAT_CTRL_REGS__

#ifndef __ADC_SAT_LANE1_INIT_MASK__
#define __ADC_SAT_LANE1_INIT_MASK__
#define ADC_SAT_LANE1_INIT_MASK(x) (x)->adc_sat_lane1_init_mask_register.adc_sat_lane1_init_mask_u.adc_sat_lane1_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_INIT_MASK(x) (x)->adc_sat_lane1_init_mask_register.adc_sat_lane1_init_mask_u.bits.adc_sat_lane1_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_INIT_MASK_MODE3(x) (x)->adc_sat_lane1_init_mask_register.adc_sat_lane1_init_mask_u.bits.adc_sat_lane1_init_mask_mode3
typedef volatile struct adc_sat_lane1_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane1_init_mask : 16;
			unsigned int adc_sat_lane1_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane1_init_mask;
	} adc_sat_lane1_init_mask_u;
} adc_sat_lane1_init_mask_t;
#endif /* __ADC_SAT_LANE1_INIT_MASK__ */

#ifndef __ADC_SAT_LANE2_INIT_MASK__
#define __ADC_SAT_LANE2_INIT_MASK__
#define ADC_SAT_LANE2_INIT_MASK(x) (x)->adc_sat_lane2_init_mask_register.adc_sat_lane2_init_mask_u.adc_sat_lane2_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_INIT_MASK(x) (x)->adc_sat_lane2_init_mask_register.adc_sat_lane2_init_mask_u.bits.adc_sat_lane2_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_INIT_MASK_MODE3(x) (x)->adc_sat_lane2_init_mask_register.adc_sat_lane2_init_mask_u.bits.adc_sat_lane2_init_mask_mode3
typedef volatile struct adc_sat_lane2_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane2_init_mask : 16;
			unsigned int adc_sat_lane2_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane2_init_mask;
	} adc_sat_lane2_init_mask_u;
} adc_sat_lane2_init_mask_t;
#endif /* __ADC_SAT_LANE2_INIT_MASK__ */

#ifndef __ADC_SAT_LANE3_INIT_MASK__
#define __ADC_SAT_LANE3_INIT_MASK__
#define ADC_SAT_LANE3_INIT_MASK(x) (x)->adc_sat_lane3_init_mask_register.adc_sat_lane3_init_mask_u.adc_sat_lane3_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_INIT_MASK(x) (x)->adc_sat_lane3_init_mask_register.adc_sat_lane3_init_mask_u.bits.adc_sat_lane3_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_INIT_MASK_MODE3(x) (x)->adc_sat_lane3_init_mask_register.adc_sat_lane3_init_mask_u.bits.adc_sat_lane3_init_mask_mode3
typedef volatile struct adc_sat_lane3_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane3_init_mask : 16;
			unsigned int adc_sat_lane3_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane3_init_mask;
	} adc_sat_lane3_init_mask_u;
} adc_sat_lane3_init_mask_t;
#endif /* __ADC_SAT_LANE3_INIT_MASK__ */

#ifndef __ADC_SAT_LANE4_INIT_MASK__
#define __ADC_SAT_LANE4_INIT_MASK__
#define ADC_SAT_LANE4_INIT_MASK(x) (x)->adc_sat_lane4_init_mask_register.adc_sat_lane4_init_mask_u.adc_sat_lane4_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_INIT_MASK(x) (x)->adc_sat_lane4_init_mask_register.adc_sat_lane4_init_mask_u.bits.adc_sat_lane4_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_INIT_MASK_MODE3(x) (x)->adc_sat_lane4_init_mask_register.adc_sat_lane4_init_mask_u.bits.adc_sat_lane4_init_mask_mode3
typedef volatile struct adc_sat_lane4_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane4_init_mask : 16;
			unsigned int adc_sat_lane4_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane4_init_mask;
	} adc_sat_lane4_init_mask_u;
} adc_sat_lane4_init_mask_t;
#endif /* __ADC_SAT_LANE4_INIT_MASK__ */

#ifndef __ADC_SAT_LANE5_INIT_MASK__
#define __ADC_SAT_LANE5_INIT_MASK__
#define ADC_SAT_LANE5_INIT_MASK(x) (x)->adc_sat_lane5_init_mask_register.adc_sat_lane5_init_mask_u.adc_sat_lane5_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_INIT_MASK(x) (x)->adc_sat_lane5_init_mask_register.adc_sat_lane5_init_mask_u.bits.adc_sat_lane5_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_INIT_MASK_MODE3(x) (x)->adc_sat_lane5_init_mask_register.adc_sat_lane5_init_mask_u.bits.adc_sat_lane5_init_mask_mode3
typedef volatile struct adc_sat_lane5_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane5_init_mask : 16;
			unsigned int adc_sat_lane5_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane5_init_mask;
	} adc_sat_lane5_init_mask_u;
} adc_sat_lane5_init_mask_t;
#endif /* __ADC_SAT_LANE5_INIT_MASK__ */

#ifndef __ADC_SAT_LANE6_INIT_MASK__
#define __ADC_SAT_LANE6_INIT_MASK__
#define ADC_SAT_LANE6_INIT_MASK(x) (x)->adc_sat_lane6_init_mask_register.adc_sat_lane6_init_mask_u.adc_sat_lane6_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_INIT_MASK(x) (x)->adc_sat_lane6_init_mask_register.adc_sat_lane6_init_mask_u.bits.adc_sat_lane6_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_INIT_MASK_MODE3(x) (x)->adc_sat_lane6_init_mask_register.adc_sat_lane6_init_mask_u.bits.adc_sat_lane6_init_mask_mode3
typedef volatile struct adc_sat_lane6_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane6_init_mask : 16;
			unsigned int adc_sat_lane6_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane6_init_mask;
	} adc_sat_lane6_init_mask_u;
} adc_sat_lane6_init_mask_t;
#endif /* __ADC_SAT_LANE6_INIT_MASK__ */

#ifndef __ADC_SAT_LANE7_INIT_MASK__
#define __ADC_SAT_LANE7_INIT_MASK__
#define ADC_SAT_LANE7_INIT_MASK(x) (x)->adc_sat_lane7_init_mask_register.adc_sat_lane7_init_mask_u.adc_sat_lane7_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_INIT_MASK(x) (x)->adc_sat_lane7_init_mask_register.adc_sat_lane7_init_mask_u.bits.adc_sat_lane7_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_INIT_MASK_MODE3(x) (x)->adc_sat_lane7_init_mask_register.adc_sat_lane7_init_mask_u.bits.adc_sat_lane7_init_mask_mode3
typedef volatile struct adc_sat_lane7_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane7_init_mask : 16;
			unsigned int adc_sat_lane7_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane7_init_mask;
	} adc_sat_lane7_init_mask_u;
} adc_sat_lane7_init_mask_t;
#endif /* __ADC_SAT_LANE7_INIT_MASK__ */

#ifndef __ADC_SAT_LANE8_INIT_MASK__
#define __ADC_SAT_LANE8_INIT_MASK__
#define ADC_SAT_LANE8_INIT_MASK(x) (x)->adc_sat_lane8_init_mask_register.adc_sat_lane8_init_mask_u.adc_sat_lane8_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_INIT_MASK(x) (x)->adc_sat_lane8_init_mask_register.adc_sat_lane8_init_mask_u.bits.adc_sat_lane8_init_mask
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_INIT_MASK_MODE3(x) (x)->adc_sat_lane8_init_mask_register.adc_sat_lane8_init_mask_u.bits.adc_sat_lane8_init_mask_mode3
typedef volatile struct adc_sat_lane8_init_mask_s {
	union {
		struct {
			unsigned int adc_sat_lane8_init_mask : 16;
			unsigned int adc_sat_lane8_init_mask_mode3 : 16;
		} bits;
		uint32_t adc_sat_lane8_init_mask;
	} adc_sat_lane8_init_mask_u;
} adc_sat_lane8_init_mask_t;
#endif /* __ADC_SAT_LANE8_INIT_MASK__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_1__
#define __ADC_SAT_SHIFT_CTRL_LANE_1__
#define ADC_SAT_SHIFT_CTRL_LANE_1(x) (x)->adc_sat_shift_ctrl_lane_1_register.adc_sat_shift_ctrl_lane_1_u.adc_sat_shift_ctrl_lane_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_1_register.adc_sat_shift_ctrl_lane_1_u.bits.adc_sat_lane1_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_1_register.adc_sat_shift_ctrl_lane_1_u.bits.adc_sat_lane1_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_1_register.adc_sat_shift_ctrl_lane_1_u.bits.adc_sat_lane1_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE1_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_1_register.adc_sat_shift_ctrl_lane_1_u.bits.adc_sat_lane1_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_1_s {
	union {
		struct {
			unsigned int adc_sat_lane1_shift_0 : 3;
			unsigned int adc_sat_lane1_shift_1 : 3;
			unsigned int adc_sat_lane1_shift_2 : 3;
			unsigned int adc_sat_lane1_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_1;
	} adc_sat_shift_ctrl_lane_1_u;
} adc_sat_shift_ctrl_lane_1_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_1__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_2__
#define __ADC_SAT_SHIFT_CTRL_LANE_2__
#define ADC_SAT_SHIFT_CTRL_LANE_2(x) (x)->adc_sat_shift_ctrl_lane_2_register.adc_sat_shift_ctrl_lane_2_u.adc_sat_shift_ctrl_lane_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_2_register.adc_sat_shift_ctrl_lane_2_u.bits.adc_sat_lane2_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_2_register.adc_sat_shift_ctrl_lane_2_u.bits.adc_sat_lane2_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_2_register.adc_sat_shift_ctrl_lane_2_u.bits.adc_sat_lane2_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE2_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_2_register.adc_sat_shift_ctrl_lane_2_u.bits.adc_sat_lane2_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_2_s {
	union {
		struct {
			unsigned int adc_sat_lane2_shift_0 : 3;
			unsigned int adc_sat_lane2_shift_1 : 3;
			unsigned int adc_sat_lane2_shift_2 : 3;
			unsigned int adc_sat_lane2_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_2;
	} adc_sat_shift_ctrl_lane_2_u;
} adc_sat_shift_ctrl_lane_2_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_2__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_3__
#define __ADC_SAT_SHIFT_CTRL_LANE_3__
#define ADC_SAT_SHIFT_CTRL_LANE_3(x) (x)->adc_sat_shift_ctrl_lane_3_register.adc_sat_shift_ctrl_lane_3_u.adc_sat_shift_ctrl_lane_3
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_3_register.adc_sat_shift_ctrl_lane_3_u.bits.adc_sat_lane3_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_3_register.adc_sat_shift_ctrl_lane_3_u.bits.adc_sat_lane3_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_3_register.adc_sat_shift_ctrl_lane_3_u.bits.adc_sat_lane3_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE3_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_3_register.adc_sat_shift_ctrl_lane_3_u.bits.adc_sat_lane3_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_3_s {
	union {
		struct {
			unsigned int adc_sat_lane3_shift_0 : 3;
			unsigned int adc_sat_lane3_shift_1 : 3;
			unsigned int adc_sat_lane3_shift_2 : 3;
			unsigned int adc_sat_lane3_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_3;
	} adc_sat_shift_ctrl_lane_3_u;
} adc_sat_shift_ctrl_lane_3_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_3__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_4__
#define __ADC_SAT_SHIFT_CTRL_LANE_4__
#define ADC_SAT_SHIFT_CTRL_LANE_4(x) (x)->adc_sat_shift_ctrl_lane_4_register.adc_sat_shift_ctrl_lane_4_u.adc_sat_shift_ctrl_lane_4
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_4_register.adc_sat_shift_ctrl_lane_4_u.bits.adc_sat_lane4_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_4_register.adc_sat_shift_ctrl_lane_4_u.bits.adc_sat_lane4_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_4_register.adc_sat_shift_ctrl_lane_4_u.bits.adc_sat_lane4_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE4_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_4_register.adc_sat_shift_ctrl_lane_4_u.bits.adc_sat_lane4_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_4_s {
	union {
		struct {
			unsigned int adc_sat_lane4_shift_0 : 3;
			unsigned int adc_sat_lane4_shift_1 : 3;
			unsigned int adc_sat_lane4_shift_2 : 3;
			unsigned int adc_sat_lane4_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_4;
	} adc_sat_shift_ctrl_lane_4_u;
} adc_sat_shift_ctrl_lane_4_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_4__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_5__
#define __ADC_SAT_SHIFT_CTRL_LANE_5__
#define ADC_SAT_SHIFT_CTRL_LANE_5(x) (x)->adc_sat_shift_ctrl_lane_5_register.adc_sat_shift_ctrl_lane_5_u.adc_sat_shift_ctrl_lane_5
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_5_register.adc_sat_shift_ctrl_lane_5_u.bits.adc_sat_lane5_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_5_register.adc_sat_shift_ctrl_lane_5_u.bits.adc_sat_lane5_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_5_register.adc_sat_shift_ctrl_lane_5_u.bits.adc_sat_lane5_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE5_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_5_register.adc_sat_shift_ctrl_lane_5_u.bits.adc_sat_lane5_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_5_s {
	union {
		struct {
			unsigned int adc_sat_lane5_shift_0 : 3;
			unsigned int adc_sat_lane5_shift_1 : 3;
			unsigned int adc_sat_lane5_shift_2 : 3;
			unsigned int adc_sat_lane5_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_5;
	} adc_sat_shift_ctrl_lane_5_u;
} adc_sat_shift_ctrl_lane_5_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_5__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_6__
#define __ADC_SAT_SHIFT_CTRL_LANE_6__
#define ADC_SAT_SHIFT_CTRL_LANE_6(x) (x)->adc_sat_shift_ctrl_lane_6_register.adc_sat_shift_ctrl_lane_6_u.adc_sat_shift_ctrl_lane_6
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_6_register.adc_sat_shift_ctrl_lane_6_u.bits.adc_sat_lane6_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_6_register.adc_sat_shift_ctrl_lane_6_u.bits.adc_sat_lane6_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_6_register.adc_sat_shift_ctrl_lane_6_u.bits.adc_sat_lane6_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE6_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_6_register.adc_sat_shift_ctrl_lane_6_u.bits.adc_sat_lane6_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_6_s {
	union {
		struct {
			unsigned int adc_sat_lane6_shift_0 : 3;
			unsigned int adc_sat_lane6_shift_1 : 3;
			unsigned int adc_sat_lane6_shift_2 : 3;
			unsigned int adc_sat_lane6_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_6;
	} adc_sat_shift_ctrl_lane_6_u;
} adc_sat_shift_ctrl_lane_6_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_6__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_7__
#define __ADC_SAT_SHIFT_CTRL_LANE_7__
#define ADC_SAT_SHIFT_CTRL_LANE_7(x) (x)->adc_sat_shift_ctrl_lane_7_register.adc_sat_shift_ctrl_lane_7_u.adc_sat_shift_ctrl_lane_7
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_7_register.adc_sat_shift_ctrl_lane_7_u.bits.adc_sat_lane7_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_7_register.adc_sat_shift_ctrl_lane_7_u.bits.adc_sat_lane7_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_7_register.adc_sat_shift_ctrl_lane_7_u.bits.adc_sat_lane7_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE7_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_7_register.adc_sat_shift_ctrl_lane_7_u.bits.adc_sat_lane7_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_7_s {
	union {
		struct {
			unsigned int adc_sat_lane7_shift_0 : 3;
			unsigned int adc_sat_lane7_shift_1 : 3;
			unsigned int adc_sat_lane7_shift_2 : 3;
			unsigned int adc_sat_lane7_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_7;
	} adc_sat_shift_ctrl_lane_7_u;
} adc_sat_shift_ctrl_lane_7_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_7__ */

#ifndef __ADC_SAT_SHIFT_CTRL_LANE_8__
#define __ADC_SAT_SHIFT_CTRL_LANE_8__
#define ADC_SAT_SHIFT_CTRL_LANE_8(x) (x)->adc_sat_shift_ctrl_lane_8_register.adc_sat_shift_ctrl_lane_8_u.adc_sat_shift_ctrl_lane_8
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_SHIFT_0(x) (x)->adc_sat_shift_ctrl_lane_8_register.adc_sat_shift_ctrl_lane_8_u.bits.adc_sat_lane8_shift_0
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_SHIFT_1(x) (x)->adc_sat_shift_ctrl_lane_8_register.adc_sat_shift_ctrl_lane_8_u.bits.adc_sat_lane8_shift_1
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_SHIFT_2(x) (x)->adc_sat_shift_ctrl_lane_8_register.adc_sat_shift_ctrl_lane_8_u.bits.adc_sat_lane8_shift_2
#define imola_sat_ctrl_regs_ADC_SAT_LANE8_SHIFT_3(x) (x)->adc_sat_shift_ctrl_lane_8_register.adc_sat_shift_ctrl_lane_8_u.bits.adc_sat_lane8_shift_3
typedef volatile struct adc_sat_shift_ctrl_lane_8_s {
	union {
		struct {
			unsigned int adc_sat_lane8_shift_0 : 3;
			unsigned int adc_sat_lane8_shift_1 : 3;
			unsigned int adc_sat_lane8_shift_2 : 3;
			unsigned int adc_sat_lane8_shift_3 : 3;
		} bits;
		uint32_t adc_sat_shift_ctrl_lane_8;
	} adc_sat_shift_ctrl_lane_8_u;
} adc_sat_shift_ctrl_lane_8_t;
#endif /* __ADC_SAT_SHIFT_CTRL_LANE_8__ */

#ifndef __DAC_SAT_COUNTERS_1__
#define __DAC_SAT_COUNTERS_1__
#define DAC_SAT_COUNTERS_1(x) (x)->dac_sat_counters_1_register.dac_sat_counters_1_u.dac_sat_counters_1
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_0(x) (x)->dac_sat_counters_1_register.dac_sat_counters_1_u.bits.dac_sat_counter_0
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_1(x) (x)->dac_sat_counters_1_register.dac_sat_counters_1_u.bits.dac_sat_counter_1
typedef volatile struct dac_sat_counters_1_s {
	union {
		struct {
			unsigned int dac_sat_counter_0 : 16;
			unsigned int dac_sat_counter_1 : 16;
		} bits;
		uint32_t dac_sat_counters_1;
	} dac_sat_counters_1_u;
} dac_sat_counters_1_t;
#endif /* __DAC_SAT_COUNTERS_1__ */

#ifndef __DAC_SAT_COUNTERS_2__
#define __DAC_SAT_COUNTERS_2__
#define DAC_SAT_COUNTERS_2(x) (x)->dac_sat_counters_2_register.dac_sat_counters_2_u.dac_sat_counters_2
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_2(x) (x)->dac_sat_counters_2_register.dac_sat_counters_2_u.bits.dac_sat_counter_2
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_3(x) (x)->dac_sat_counters_2_register.dac_sat_counters_2_u.bits.dac_sat_counter_3
typedef volatile struct dac_sat_counters_2_s {
	union {
		struct {
			unsigned int dac_sat_counter_2 : 16;
			unsigned int dac_sat_counter_3 : 16;
		} bits;
		uint32_t dac_sat_counters_2;
	} dac_sat_counters_2_u;
} dac_sat_counters_2_t;
#endif /* __DAC_SAT_COUNTERS_2__ */

#ifndef __DAC_SAT_COUNTERS_3__
#define __DAC_SAT_COUNTERS_3__
#define DAC_SAT_COUNTERS_3(x) (x)->dac_sat_counters_3_register.dac_sat_counters_3_u.dac_sat_counters_3
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_4(x) (x)->dac_sat_counters_3_register.dac_sat_counters_3_u.bits.dac_sat_counter_4
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_5(x) (x)->dac_sat_counters_3_register.dac_sat_counters_3_u.bits.dac_sat_counter_5
typedef volatile struct dac_sat_counters_3_s {
	union {
		struct {
			unsigned int dac_sat_counter_4 : 16;
			unsigned int dac_sat_counter_5 : 16;
		} bits;
		uint32_t dac_sat_counters_3;
	} dac_sat_counters_3_u;
} dac_sat_counters_3_t;
#endif /* __DAC_SAT_COUNTERS_3__ */

#ifndef __DAC_SAT_COUNTERS_4__
#define __DAC_SAT_COUNTERS_4__
#define DAC_SAT_COUNTERS_4(x) (x)->dac_sat_counters_4_register.dac_sat_counters_4_u.dac_sat_counters_4
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_6(x) (x)->dac_sat_counters_4_register.dac_sat_counters_4_u.bits.dac_sat_counter_6
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_7(x) (x)->dac_sat_counters_4_register.dac_sat_counters_4_u.bits.dac_sat_counter_7
typedef volatile struct dac_sat_counters_4_s {
	union {
		struct {
			unsigned int dac_sat_counter_6 : 16;
			unsigned int dac_sat_counter_7 : 16;
		} bits;
		uint32_t dac_sat_counters_4;
	} dac_sat_counters_4_u;
} dac_sat_counters_4_t;
#endif /* __DAC_SAT_COUNTERS_4__ */

#ifndef __DAC_SAT_COUNTERS_5__
#define __DAC_SAT_COUNTERS_5__
#define DAC_SAT_COUNTERS_5(x) (x)->dac_sat_counters_5_register.dac_sat_counters_5_u.dac_sat_counters_5
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_8(x) (x)->dac_sat_counters_5_register.dac_sat_counters_5_u.bits.dac_sat_counter_8
#define imola_sat_ctrl_regs_DAC_SAT_COUNTER_9(x) (x)->dac_sat_counters_5_register.dac_sat_counters_5_u.bits.dac_sat_counter_9
typedef volatile struct dac_sat_counters_5_s {
	union {
		struct {
			unsigned int dac_sat_counter_8 : 16;
			unsigned int dac_sat_counter_9 : 16;
		} bits;
		uint32_t dac_sat_counters_5;
	} dac_sat_counters_5_u;
} dac_sat_counters_5_t;
#endif /* __DAC_SAT_COUNTERS_5__ */

#ifndef __SAT_SELF_CLEARING__
#define __SAT_SELF_CLEARING__
#define SAT_SELF_CLEARING(x) (x)->sat_self_clearing_register.sat_self_clearing_u.sat_self_clearing
#define imola_sat_ctrl_regs_CLEAR_DAC_SAT_COUNTERS(x) (x)->sat_self_clearing_register.sat_self_clearing_u.bits.clear_dac_sat_counters
typedef volatile struct sat_self_clearing_s {
	union {
		struct {
			unsigned int clear_dac_sat_counters : 1;
		} bits;
		uint32_t sat_self_clearing;
	} sat_self_clearing_u;
} sat_self_clearing_t;
#endif /* __SAT_SELF_CLEARING__ */

#ifndef __ADC_SAT_LANE_DISABLE__
#define __ADC_SAT_LANE_DISABLE__
#define ADC_SAT_LANE_DISABLE(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.adc_sat_lane_disable
#define imola_sat_ctrl_regs_ADC_LANE1_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane1_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE2_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane2_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE3_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane3_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE4_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane4_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE5_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane5_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE6_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane6_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE7_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane7_disable_bits
#define imola_sat_ctrl_regs_ADC_LANE8_DISABLE_BITS(x) (x)->adc_sat_lane_disable_register.adc_sat_lane_disable_u.bits.adc_lane8_disable_bits
typedef volatile struct adc_sat_lane_disable_s {
	union {
		struct {
			unsigned int adc_lane1_disable_bits : 4;
			unsigned int adc_lane2_disable_bits : 4;
			unsigned int adc_lane3_disable_bits : 4;
			unsigned int adc_lane4_disable_bits : 4;
			unsigned int adc_lane5_disable_bits : 4;
			unsigned int adc_lane6_disable_bits : 4;
			unsigned int adc_lane7_disable_bits : 4;
			unsigned int adc_lane8_disable_bits : 4;
		} bits;
		uint32_t adc_sat_lane_disable;
	} adc_sat_lane_disable_u;
} adc_sat_lane_disable_t;
#endif /* __ADC_SAT_LANE_DISABLE__ */

#ifndef __ADC_SAT_SHIFT__
#define __ADC_SAT_SHIFT__
#define ADC_SAT_SHIFT(x) (x)->adc_sat_shift_register.adc_sat_shift_u.adc_sat_shift
#define imola_sat_ctrl_regs_ADC_SAT_SHIFT(x) (x)->adc_sat_shift_register.adc_sat_shift_u.bits.adc_sat_shift
typedef volatile struct adc_sat_shift_s {
	union {
		struct {
			unsigned int adc_sat_shift : 3;
		} bits;
		uint32_t adc_sat_shift;
	} adc_sat_shift_u;
} adc_sat_shift_t;
#endif /* __ADC_SAT_SHIFT__ */

typedef struct imola_sat_ctrl_regs_s
{
	adc_sat_lane1_init_mask_t adc_sat_lane1_init_mask_register;	// Address: 0x0
	adc_sat_lane2_init_mask_t adc_sat_lane2_init_mask_register;	// Address: 0x1
	adc_sat_lane3_init_mask_t adc_sat_lane3_init_mask_register;	// Address: 0x2
	adc_sat_lane4_init_mask_t adc_sat_lane4_init_mask_register;	// Address: 0x3
	adc_sat_lane5_init_mask_t adc_sat_lane5_init_mask_register;	// Address: 0x4
	adc_sat_lane6_init_mask_t adc_sat_lane6_init_mask_register;	// Address: 0x5
	adc_sat_lane7_init_mask_t adc_sat_lane7_init_mask_register;	// Address: 0x6
	adc_sat_lane8_init_mask_t adc_sat_lane8_init_mask_register;	// Address: 0x7
	adc_sat_shift_ctrl_lane_1_t adc_sat_shift_ctrl_lane_1_register;	// Address: 0x8
	adc_sat_shift_ctrl_lane_2_t adc_sat_shift_ctrl_lane_2_register;	// Address: 0x9
	adc_sat_shift_ctrl_lane_3_t adc_sat_shift_ctrl_lane_3_register;	// Address: 0xa
	adc_sat_shift_ctrl_lane_4_t adc_sat_shift_ctrl_lane_4_register;	// Address: 0xb
	adc_sat_shift_ctrl_lane_5_t adc_sat_shift_ctrl_lane_5_register;	// Address: 0xc
	adc_sat_shift_ctrl_lane_6_t adc_sat_shift_ctrl_lane_6_register;	// Address: 0xd
	adc_sat_shift_ctrl_lane_7_t adc_sat_shift_ctrl_lane_7_register;	// Address: 0xe
	adc_sat_shift_ctrl_lane_8_t adc_sat_shift_ctrl_lane_8_register;	// Address: 0xf
	dac_sat_counters_1_t dac_sat_counters_1_register;	// Address: 0x10
	dac_sat_counters_2_t dac_sat_counters_2_register;	// Address: 0x11
	dac_sat_counters_3_t dac_sat_counters_3_register;	// Address: 0x12
	dac_sat_counters_4_t dac_sat_counters_4_register;	// Address: 0x13
	dac_sat_counters_5_t dac_sat_counters_5_register;	// Address: 0x14
	sat_self_clearing_t sat_self_clearing_register;	// Address: 0x15
	adc_sat_lane_disable_t adc_sat_lane_disable_register;	// Address: 0x16
	adc_sat_shift_t adc_sat_shift_register;	// Address: 0x17
} imola_sat_ctrl_regs_t;

#endif /* __IMOLA_SAT_CTRL_REGS__ */
