//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __OOB_ETB_HXX__
#define __OOB_ETB_HXX__

#define OOB_ETB_ETB_CONTROL          (REG_OOB_ETB+0x0)
#define OOB_ETB_ETB_STATUS           (REG_OOB_ETB+0x4)
#define OOB_ETB_RD_TRACE_REG_2       (REG_OOB_ETB+0x8)
#define OOB_ETB_RD_TRACE_REG_1       (REG_OOB_ETB+0xc)
#define OOB_ETB_RD_TRACE_REG_0       (REG_OOB_ETB+0x10)
#define OOB_ETB_TRACE_SRAM0_CONTROL  (REG_OOB_ETB+0x14)
#define OOB_ETB_TRACE_SRAM1_CONTROL  (REG_OOB_ETB+0x18)
#define OOB_ETB_ETB_SELF_CLEARING    (REG_OOB_ETB+0x1c)

#endif /* __OOB_ETB_HXX__ */
