//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __OOB_AXIFACE_HXX__
#define __OOB_AXIFACE_HXX__

#define OOB_AXIFACE_OOB_AXIFACE_CONTROL                    (REG_OOB_AXIFACE+0x0)
#define OOB_AXIFACE_OOB_AXIFACE_STATUS                     (REG_OOB_AXIFACE+0x4)
#define OOB_AXIFACE_AXI_BUS_STATUS                         (REG_OOB_AXIFACE+0x8)
#define OOB_AXIFACE_NUM_AXI_WRITE_REQUESTS_AND_COMPLETION  (REG_OOB_AXIFACE+0xc)
#define OOB_AXIFACE_NUM_AXI_READ_REQUESTS_AND_COMPLETION   (REG_OOB_AXIFACE+0x10)
#define OOB_AXIFACE_WRITE_FIFO_SIGNALS                     (REG_OOB_AXIFACE+0x14)

#endif /* __OOB_AXIFACE_HXX__ */
