//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __OOB_MERLIN_HXX__
#define __OOB_MERLIN_HXX__

#define OOB_MERLIN_FRAMER_CONTROLLER_CONTROL       (REG_OOB_MERLIN+0x0)
#define OOB_MERLIN_FRAMER_CONTROLLER_STATUS        (REG_OOB_MERLIN+0x4)
#define OOB_MERLIN_TRIGGER_CONTROL                 (REG_OOB_MERLIN+0x8)
#define OOB_MERLIN_WR_MICROCODE_REG_2              (REG_OOB_MERLIN+0xc)
#define OOB_MERLIN_WR_MICROCODE_REG_1              (REG_OOB_MERLIN+0x10)
#define OOB_MERLIN_WR_MICROCODE_REG_0              (REG_OOB_MERLIN+0x14)
#define OOB_MERLIN_MICROCODE_SRAM_BYTE_WRITE_MASK  (REG_OOB_MERLIN+0x18)
#define OOB_MERLIN_MICROCODE_SRAM_CONTROL          (REG_OOB_MERLIN+0x1c)
#define OOB_MERLIN_WAIT_NOP_REGISTERS              (REG_OOB_MERLIN+0x20)
#define OOB_MERLIN_DEBUG_CONTROL                   (REG_OOB_MERLIN+0x24)
#define OOB_MERLIN_DEBUG_DATA                      (REG_OOB_MERLIN+0x28)
#define OOB_MERLIN_SELF_CLEARING                   (REG_OOB_MERLIN+0x2c)

#endif /* __OOB_MERLIN_HXX__ */
