//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __OOB_PROC_HXX__
#define __OOB_PROC_HXX__

#define OOB_PROC_OOB_PROC_CONTROL                (REG_OOB_PROC+0x0)
#define OOB_PROC_OOB_PROC_STATUS                 (REG_OOB_PROC+0x4)
#define OOB_PROC_OOB_REGS2DP                     (REG_OOB_PROC+0x8)
#define OOB_PROC_AXI_BUS_FIFO_WR_DATA            (REG_OOB_PROC+0xc)
#define OOB_PROC_AXI_BUS_FIFO_RD_DATA            (REG_OOB_PROC+0x10)
#define OOB_PROC_AXI_BUS_FIFO_ADDR               (REG_OOB_PROC+0x14)
#define OOB_PROC_OOB_PROC_ERROR_BITS             (REG_OOB_PROC+0x18)
#define OOB_PROC_OOB_PROC_SELF_CLEAR_ERROR_BITS  (REG_OOB_PROC+0x1c)
#define OOB_PROC_OOB_REGS2PERIPH                 (REG_OOB_PROC+0x20)
#define OOB_PROC_FRAME_FMT_TABLE2PERIPH          (REG_OOB_PROC+0x24)

#endif /* __OOB_PROC_HXX__ */
