//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __PAD_CTRL_HXX__
#define __PAD_CTRL_HXX__

#define PAD_CTRL_BOOT_MODE               (REG_PAD_CTRL+0x0)
#define PAD_CTRL_PAD_MISC_CONFIG         (REG_PAD_CTRL+0x4)
#define PAD_CTRL_PAD_GPIO_CONFIG0        (REG_PAD_CTRL+0x8)
#define PAD_CTRL_PAD_GPIO_CONFIG1        (REG_PAD_CTRL+0xc)
#define PAD_CTRL_PAD_GPIO_CONFIG2        (REG_PAD_CTRL+0x10)
#define PAD_CTRL_PAD_GPIO_CONFIG3        (REG_PAD_CTRL+0x14)
#define PAD_CTRL_PAD_MUX_CONFIG          (REG_PAD_CTRL+0x18)
#define PAD_CTRL_CLK_RECV_CONFIG1        (REG_PAD_CTRL+0x1c)
#define PAD_CTRL_CLK_RECV_CONFIG2        (REG_PAD_CTRL+0x20)
#define PAD_CTRL_CLK_RECV_STATUS         (REG_PAD_CTRL+0x24)
#define PAD_CTRL_CLK_RX_PK_DET_REGS      (REG_PAD_CTRL+0x28)
#define PAD_CTRL_ANALOG_COMMON_CTRL      (REG_PAD_CTRL+0x2c)
#define PAD_CTRL_ANALOG_BGAP_CTRL        (REG_PAD_CTRL+0x30)
#define PAD_CTRL_SERDES_PHY_COMMON_CTRL  (REG_PAD_CTRL+0x34)
#define PAD_CTRL_SERDES_PHY_BGAP_CTRL    (REG_PAD_CTRL+0x38)

#endif /* __PAD_CTRL_HXX__ */
