//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RAM_PARAM_HXX__
#define __RAM_PARAM_HXX__

#define RAM_PARAM_SRAM_SHARE_BITS  (REG_RAM_PARAM+0x0)
#define RAM_PARAM_IRAM_CONFIG_0    (REG_RAM_PARAM+0x4)
#define RAM_PARAM_IRAM_CONFIG_1    (REG_RAM_PARAM+0x8)
#define RAM_PARAM_IRAM_CONFIG_2    (REG_RAM_PARAM+0xc)
#define RAM_PARAM_IRAM_CONFIG_3    (REG_RAM_PARAM+0x10)
#define RAM_PARAM_IRAM_CONFIG_4    (REG_RAM_PARAM+0x14)
#define RAM_PARAM_IRAM_CONFIG_5    (REG_RAM_PARAM+0x18)
#define RAM_PARAM_IRAM_CONFIG_6    (REG_RAM_PARAM+0x1c)
#define RAM_PARAM_IRAM_CONFIG_7    (REG_RAM_PARAM+0x20)
#define RAM_PARAM_DRAM_CONFIG_0    (REG_RAM_PARAM+0x24)
#define RAM_PARAM_DRAM_CONFIG_1    (REG_RAM_PARAM+0x28)
#define RAM_PARAM_DRAM_CONFIG_2    (REG_RAM_PARAM+0x2c)
#define RAM_PARAM_DRAM_CONFIG_3    (REG_RAM_PARAM+0x30)

#endif /* __RAM_PARAM_HXX__ */
