//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RISCV_UART_HXX__
#define __RISCV_UART_HXX__

#define RISCV_UART_RBR_DLL  (REG_RISCV_UART+0x0)
#define RISCV_UART_THR_DLM  (REG_RISCV_UART+0x4)
#define RISCV_UART_IER_FCR  (REG_RISCV_UART+0x8)
#define RISCV_UART_LCR      (REG_RISCV_UART+0xc)
#define RISCV_UART_MCR      (REG_RISCV_UART+0x10)
#define RISCV_UART_LSR      (REG_RISCV_UART+0x14)
#define RISCV_UART_MSR      (REG_RISCV_UART+0x18)
#define RISCV_UART_SCR      (REG_RISCV_UART+0x1c)

#endif /* __RISCV_UART_HXX__ */
