//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_CDR_HXX__
#define __RX_CDR_HXX__

#define RX_CDR_RX_CDR_RESET_CTRL             (REG_RX_CDR+0x4)
#define RX_CDR_RX_CDR_CLK_POLARITY           (REG_RX_CDR+0x8)
#define RX_CDR_RX_CDR_HFBOOST_LANE0          (REG_RX_CDR+0xc)
#define RX_CDR_RX_CDR_HFBOOST_LANE1          (REG_RX_CDR+0x10)
#define RX_CDR_RX_CDR_HFBOOST_LANE2          (REG_RX_CDR+0x14)
#define RX_CDR_RX_CDR_HFBOOST_LANE3          (REG_RX_CDR+0x18)
#define RX_CDR_RX_CDR_HFBOOST_LANE4          (REG_RX_CDR+0x1c)
#define RX_CDR_RX_CDR_HFBOOST_LANE5          (REG_RX_CDR+0x20)
#define RX_CDR_RX_CDR_HFBOOST_LANE6          (REG_RX_CDR+0x24)
#define RX_CDR_RX_CDR_HFBOOST_LANE7          (REG_RX_CDR+0x28)
#define RX_CDR_RX_CDR_PD_LANE0               (REG_RX_CDR+0x2c)
#define RX_CDR_RX_CDR_PD_LANE1               (REG_RX_CDR+0x30)
#define RX_CDR_RX_CDR_PD_LANE2               (REG_RX_CDR+0x34)
#define RX_CDR_RX_CDR_PD_LANE3               (REG_RX_CDR+0x38)
#define RX_CDR_RX_CDR_PD_LANE4               (REG_RX_CDR+0x3c)
#define RX_CDR_RX_CDR_PD_LANE5               (REG_RX_CDR+0x40)
#define RX_CDR_RX_CDR_PD_LANE6               (REG_RX_CDR+0x44)
#define RX_CDR_RX_CDR_PD_LANE7               (REG_RX_CDR+0x48)
#define RX_CDR_RX_CDR_FILT_LANE0             (REG_RX_CDR+0x4c)
#define RX_CDR_RX_CDR_FILT_LANE1             (REG_RX_CDR+0x50)
#define RX_CDR_RX_CDR_FILT_LANE2             (REG_RX_CDR+0x54)
#define RX_CDR_RX_CDR_FILT_LANE3             (REG_RX_CDR+0x58)
#define RX_CDR_RX_CDR_FILT_LANE4             (REG_RX_CDR+0x5c)
#define RX_CDR_RX_CDR_FILT_LANE5             (REG_RX_CDR+0x60)
#define RX_CDR_RX_CDR_FILT_LANE6             (REG_RX_CDR+0x64)
#define RX_CDR_RX_CDR_FILT_LANE7             (REG_RX_CDR+0x68)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE0  (REG_RX_CDR+0x6c)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE1  (REG_RX_CDR+0x70)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE2  (REG_RX_CDR+0x74)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE3  (REG_RX_CDR+0x78)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE4  (REG_RX_CDR+0x7c)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE5  (REG_RX_CDR+0x80)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE6  (REG_RX_CDR+0x84)
#define RX_CDR_RX_CDR_FLEX_FIFO_STATE_LANE7  (REG_RX_CDR+0x88)
#define RX_CDR_RX_CDR_MODE                   (REG_RX_CDR+0x8c)
#define RX_CDR_RX_CDR_SDR_MODE               (REG_RX_CDR+0x90)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE0         (REG_RX_CDR+0x94)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE1         (REG_RX_CDR+0x98)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE2         (REG_RX_CDR+0x9c)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE3         (REG_RX_CDR+0xa0)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE4         (REG_RX_CDR+0xa4)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE5         (REG_RX_CDR+0xa8)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE6         (REG_RX_CDR+0xac)
#define RX_CDR_RX_CDR_AMP_BIAS_LANE7         (REG_RX_CDR+0xb0)
#define RX_CDR_RX_CDR_LANE_EN                (REG_RX_CDR+0xb4)

#endif /* __RX_CDR_HXX__ */
