//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM v3.1.4
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_CDR_REGS__
#define __RX_CDR_REGS__

#ifndef __RX_CDR_RESET_CTRL__
#define __RX_CDR_RESET_CTRL__
#define RX_CDR_RESET_CTRL(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.rx_cdr_reset_ctrl
#define rx_cdr_regs_LANE0_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane0_rst_n
#define rx_cdr_regs_LANE1_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane1_rst_n
#define rx_cdr_regs_LANE2_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane2_rst_n
#define rx_cdr_regs_LANE3_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane3_rst_n
#define rx_cdr_regs_LANE4_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane4_rst_n
#define rx_cdr_regs_LANE5_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane5_rst_n
#define rx_cdr_regs_LANE6_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane6_rst_n
#define rx_cdr_regs_LANE7_RST_N(x) (x)->rx_cdr_reset_ctrl_register.rx_cdr_reset_ctrl_u.bits.lane7_rst_n
typedef volatile struct rx_cdr_reset_ctrl_s {
	union {
		struct {
			unsigned int lane0_rst_n : 1;
			unsigned int lane1_rst_n : 1;
			unsigned int lane2_rst_n : 1;
			unsigned int lane3_rst_n : 1;
			unsigned int lane4_rst_n : 1;
			unsigned int lane5_rst_n : 1;
			unsigned int lane6_rst_n : 1;
			unsigned int lane7_rst_n : 1;
		} bits;
		uint32_t rx_cdr_reset_ctrl;
	} rx_cdr_reset_ctrl_u;
} rx_cdr_reset_ctrl_t;
#endif /* __RX_CDR_RESET_CTRL__ */

#ifndef __RX_CDR_CLK_POLARITY__
#define __RX_CDR_CLK_POLARITY__
#define RX_CDR_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.rx_cdr_clk_polarity
#define rx_cdr_regs_LANE0_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane0_clk_polarity
#define rx_cdr_regs_LANE1_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane1_clk_polarity
#define rx_cdr_regs_LANE2_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane2_clk_polarity
#define rx_cdr_regs_LANE3_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane3_clk_polarity
#define rx_cdr_regs_LANE4_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane4_clk_polarity
#define rx_cdr_regs_LANE5_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane5_clk_polarity
#define rx_cdr_regs_LANE6_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane6_clk_polarity
#define rx_cdr_regs_LANE7_CLK_POLARITY(x) (x)->rx_cdr_clk_polarity_register.rx_cdr_clk_polarity_u.bits.lane7_clk_polarity
typedef volatile struct rx_cdr_clk_polarity_s {
	union {
		struct {
			unsigned int lane0_clk_polarity : 1;
			unsigned int lane1_clk_polarity : 1;
			unsigned int lane2_clk_polarity : 1;
			unsigned int lane3_clk_polarity : 1;
			unsigned int lane4_clk_polarity : 1;
			unsigned int lane5_clk_polarity : 1;
			unsigned int lane6_clk_polarity : 1;
			unsigned int lane7_clk_polarity : 1;
		} bits;
		uint32_t rx_cdr_clk_polarity;
	} rx_cdr_clk_polarity_u;
} rx_cdr_clk_polarity_t;
#endif /* __RX_CDR_CLK_POLARITY__ */

#ifndef __RX_CDR_HFBOOST_LANE0__
#define __RX_CDR_HFBOOST_LANE0__
#define RX_CDR_HFBOOST_LANE0(x) (x)->rx_cdr_hfboost_lane0_register.rx_cdr_hfboost_lane0_u.rx_cdr_hfboost_lane0
#define rx_cdr_regs_LANE0_HFBOOST(x) (x)->rx_cdr_hfboost_lane0_register.rx_cdr_hfboost_lane0_u.bits.lane0_hfboost
typedef volatile struct rx_cdr_hfboost_lane0_s {
	union {
		struct {
			unsigned int lane0_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane0;
	} rx_cdr_hfboost_lane0_u;
} rx_cdr_hfboost_lane0_t;
#endif /* __RX_CDR_HFBOOST_LANE0__ */

#ifndef __RX_CDR_HFBOOST_LANE1__
#define __RX_CDR_HFBOOST_LANE1__
#define RX_CDR_HFBOOST_LANE1(x) (x)->rx_cdr_hfboost_lane1_register.rx_cdr_hfboost_lane1_u.rx_cdr_hfboost_lane1
#define rx_cdr_regs_LANE1_HFBOOST(x) (x)->rx_cdr_hfboost_lane1_register.rx_cdr_hfboost_lane1_u.bits.lane1_hfboost
typedef volatile struct rx_cdr_hfboost_lane1_s {
	union {
		struct {
			unsigned int lane1_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane1;
	} rx_cdr_hfboost_lane1_u;
} rx_cdr_hfboost_lane1_t;
#endif /* __RX_CDR_HFBOOST_LANE1__ */

#ifndef __RX_CDR_HFBOOST_LANE2__
#define __RX_CDR_HFBOOST_LANE2__
#define RX_CDR_HFBOOST_LANE2(x) (x)->rx_cdr_hfboost_lane2_register.rx_cdr_hfboost_lane2_u.rx_cdr_hfboost_lane2
#define rx_cdr_regs_LANE2_HFBOOST(x) (x)->rx_cdr_hfboost_lane2_register.rx_cdr_hfboost_lane2_u.bits.lane2_hfboost
typedef volatile struct rx_cdr_hfboost_lane2_s {
	union {
		struct {
			unsigned int lane2_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane2;
	} rx_cdr_hfboost_lane2_u;
} rx_cdr_hfboost_lane2_t;
#endif /* __RX_CDR_HFBOOST_LANE2__ */

#ifndef __RX_CDR_HFBOOST_LANE3__
#define __RX_CDR_HFBOOST_LANE3__
#define RX_CDR_HFBOOST_LANE3(x) (x)->rx_cdr_hfboost_lane3_register.rx_cdr_hfboost_lane3_u.rx_cdr_hfboost_lane3
#define rx_cdr_regs_LANE3_HFBOOST(x) (x)->rx_cdr_hfboost_lane3_register.rx_cdr_hfboost_lane3_u.bits.lane3_hfboost
typedef volatile struct rx_cdr_hfboost_lane3_s {
	union {
		struct {
			unsigned int lane3_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane3;
	} rx_cdr_hfboost_lane3_u;
} rx_cdr_hfboost_lane3_t;
#endif /* __RX_CDR_HFBOOST_LANE3__ */

#ifndef __RX_CDR_HFBOOST_LANE4__
#define __RX_CDR_HFBOOST_LANE4__
#define RX_CDR_HFBOOST_LANE4(x) (x)->rx_cdr_hfboost_lane4_register.rx_cdr_hfboost_lane4_u.rx_cdr_hfboost_lane4
#define rx_cdr_regs_LANE4_HFBOOST(x) (x)->rx_cdr_hfboost_lane4_register.rx_cdr_hfboost_lane4_u.bits.lane4_hfboost
typedef volatile struct rx_cdr_hfboost_lane4_s {
	union {
		struct {
			unsigned int lane4_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane4;
	} rx_cdr_hfboost_lane4_u;
} rx_cdr_hfboost_lane4_t;
#endif /* __RX_CDR_HFBOOST_LANE4__ */

#ifndef __RX_CDR_HFBOOST_LANE5__
#define __RX_CDR_HFBOOST_LANE5__
#define RX_CDR_HFBOOST_LANE5(x) (x)->rx_cdr_hfboost_lane5_register.rx_cdr_hfboost_lane5_u.rx_cdr_hfboost_lane5
#define rx_cdr_regs_LANE5_HFBOOST(x) (x)->rx_cdr_hfboost_lane5_register.rx_cdr_hfboost_lane5_u.bits.lane5_hfboost
typedef volatile struct rx_cdr_hfboost_lane5_s {
	union {
		struct {
			unsigned int lane5_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane5;
	} rx_cdr_hfboost_lane5_u;
} rx_cdr_hfboost_lane5_t;
#endif /* __RX_CDR_HFBOOST_LANE5__ */

#ifndef __RX_CDR_HFBOOST_LANE6__
#define __RX_CDR_HFBOOST_LANE6__
#define RX_CDR_HFBOOST_LANE6(x) (x)->rx_cdr_hfboost_lane6_register.rx_cdr_hfboost_lane6_u.rx_cdr_hfboost_lane6
#define rx_cdr_regs_LANE6_HFBOOST(x) (x)->rx_cdr_hfboost_lane6_register.rx_cdr_hfboost_lane6_u.bits.lane6_hfboost
typedef volatile struct rx_cdr_hfboost_lane6_s {
	union {
		struct {
			unsigned int lane6_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane6;
	} rx_cdr_hfboost_lane6_u;
} rx_cdr_hfboost_lane6_t;
#endif /* __RX_CDR_HFBOOST_LANE6__ */

#ifndef __RX_CDR_HFBOOST_LANE7__
#define __RX_CDR_HFBOOST_LANE7__
#define RX_CDR_HFBOOST_LANE7(x) (x)->rx_cdr_hfboost_lane7_register.rx_cdr_hfboost_lane7_u.rx_cdr_hfboost_lane7
#define rx_cdr_regs_LANE7_HFBOOST(x) (x)->rx_cdr_hfboost_lane7_register.rx_cdr_hfboost_lane7_u.bits.lane7_hfboost
typedef volatile struct rx_cdr_hfboost_lane7_s {
	union {
		struct {
			unsigned int lane7_hfboost : 8;
		} bits;
		uint32_t rx_cdr_hfboost_lane7;
	} rx_cdr_hfboost_lane7_u;
} rx_cdr_hfboost_lane7_t;
#endif /* __RX_CDR_HFBOOST_LANE7__ */

#ifndef __RX_CDR_PD_LANE0__
#define __RX_CDR_PD_LANE0__
#define RX_CDR_PD_LANE0(x) (x)->rx_cdr_pd_lane0_register.rx_cdr_pd_lane0_u.rx_cdr_pd_lane0
#define rx_cdr_regs_LANE0_PD(x) (x)->rx_cdr_pd_lane0_register.rx_cdr_pd_lane0_u.bits.lane0_pd
typedef volatile struct rx_cdr_pd_lane0_s {
	union {
		struct {
			unsigned int lane0_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane0;
	} rx_cdr_pd_lane0_u;
} rx_cdr_pd_lane0_t;
#endif /* __RX_CDR_PD_LANE0__ */

#ifndef __RX_CDR_PD_LANE1__
#define __RX_CDR_PD_LANE1__
#define RX_CDR_PD_LANE1(x) (x)->rx_cdr_pd_lane1_register.rx_cdr_pd_lane1_u.rx_cdr_pd_lane1
#define rx_cdr_regs_LANE1_PD(x) (x)->rx_cdr_pd_lane1_register.rx_cdr_pd_lane1_u.bits.lane1_pd
typedef volatile struct rx_cdr_pd_lane1_s {
	union {
		struct {
			unsigned int lane1_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane1;
	} rx_cdr_pd_lane1_u;
} rx_cdr_pd_lane1_t;
#endif /* __RX_CDR_PD_LANE1__ */

#ifndef __RX_CDR_PD_LANE2__
#define __RX_CDR_PD_LANE2__
#define RX_CDR_PD_LANE2(x) (x)->rx_cdr_pd_lane2_register.rx_cdr_pd_lane2_u.rx_cdr_pd_lane2
#define rx_cdr_regs_LANE2_PD(x) (x)->rx_cdr_pd_lane2_register.rx_cdr_pd_lane2_u.bits.lane2_pd
typedef volatile struct rx_cdr_pd_lane2_s {
	union {
		struct {
			unsigned int lane2_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane2;
	} rx_cdr_pd_lane2_u;
} rx_cdr_pd_lane2_t;
#endif /* __RX_CDR_PD_LANE2__ */

#ifndef __RX_CDR_PD_LANE3__
#define __RX_CDR_PD_LANE3__
#define RX_CDR_PD_LANE3(x) (x)->rx_cdr_pd_lane3_register.rx_cdr_pd_lane3_u.rx_cdr_pd_lane3
#define rx_cdr_regs_LANE3_PD(x) (x)->rx_cdr_pd_lane3_register.rx_cdr_pd_lane3_u.bits.lane3_pd
typedef volatile struct rx_cdr_pd_lane3_s {
	union {
		struct {
			unsigned int lane3_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane3;
	} rx_cdr_pd_lane3_u;
} rx_cdr_pd_lane3_t;
#endif /* __RX_CDR_PD_LANE3__ */

#ifndef __RX_CDR_PD_LANE4__
#define __RX_CDR_PD_LANE4__
#define RX_CDR_PD_LANE4(x) (x)->rx_cdr_pd_lane4_register.rx_cdr_pd_lane4_u.rx_cdr_pd_lane4
#define rx_cdr_regs_LANE4_PD(x) (x)->rx_cdr_pd_lane4_register.rx_cdr_pd_lane4_u.bits.lane4_pd
typedef volatile struct rx_cdr_pd_lane4_s {
	union {
		struct {
			unsigned int lane4_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane4;
	} rx_cdr_pd_lane4_u;
} rx_cdr_pd_lane4_t;
#endif /* __RX_CDR_PD_LANE4__ */

#ifndef __RX_CDR_PD_LANE5__
#define __RX_CDR_PD_LANE5__
#define RX_CDR_PD_LANE5(x) (x)->rx_cdr_pd_lane5_register.rx_cdr_pd_lane5_u.rx_cdr_pd_lane5
#define rx_cdr_regs_LANE5_PD(x) (x)->rx_cdr_pd_lane5_register.rx_cdr_pd_lane5_u.bits.lane5_pd
typedef volatile struct rx_cdr_pd_lane5_s {
	union {
		struct {
			unsigned int lane5_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane5;
	} rx_cdr_pd_lane5_u;
} rx_cdr_pd_lane5_t;
#endif /* __RX_CDR_PD_LANE5__ */

#ifndef __RX_CDR_PD_LANE6__
#define __RX_CDR_PD_LANE6__
#define RX_CDR_PD_LANE6(x) (x)->rx_cdr_pd_lane6_register.rx_cdr_pd_lane6_u.rx_cdr_pd_lane6
#define rx_cdr_regs_LANE6_PD(x) (x)->rx_cdr_pd_lane6_register.rx_cdr_pd_lane6_u.bits.lane6_pd
typedef volatile struct rx_cdr_pd_lane6_s {
	union {
		struct {
			unsigned int lane6_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane6;
	} rx_cdr_pd_lane6_u;
} rx_cdr_pd_lane6_t;
#endif /* __RX_CDR_PD_LANE6__ */

#ifndef __RX_CDR_PD_LANE7__
#define __RX_CDR_PD_LANE7__
#define RX_CDR_PD_LANE7(x) (x)->rx_cdr_pd_lane7_register.rx_cdr_pd_lane7_u.rx_cdr_pd_lane7
#define rx_cdr_regs_LANE7_PD(x) (x)->rx_cdr_pd_lane7_register.rx_cdr_pd_lane7_u.bits.lane7_pd
typedef volatile struct rx_cdr_pd_lane7_s {
	union {
		struct {
			unsigned int lane7_pd : 12;
		} bits;
		uint32_t rx_cdr_pd_lane7;
	} rx_cdr_pd_lane7_u;
} rx_cdr_pd_lane7_t;
#endif /* __RX_CDR_PD_LANE7__ */

#ifndef __RX_CDR_FILT_LANE0__
#define __RX_CDR_FILT_LANE0__
#define RX_CDR_FILT_LANE0(x) (x)->rx_cdr_filt_lane0_register.rx_cdr_filt_lane0_u.rx_cdr_filt_lane0
#define rx_cdr_regs_LANE0_FILT(x) (x)->rx_cdr_filt_lane0_register.rx_cdr_filt_lane0_u.bits.lane0_filt
typedef volatile struct rx_cdr_filt_lane0_s {
	union {
		struct {
			unsigned int lane0_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane0;
	} rx_cdr_filt_lane0_u;
} rx_cdr_filt_lane0_t;
#endif /* __RX_CDR_FILT_LANE0__ */

#ifndef __RX_CDR_FILT_LANE1__
#define __RX_CDR_FILT_LANE1__
#define RX_CDR_FILT_LANE1(x) (x)->rx_cdr_filt_lane1_register.rx_cdr_filt_lane1_u.rx_cdr_filt_lane1
#define rx_cdr_regs_LANE1_FILT(x) (x)->rx_cdr_filt_lane1_register.rx_cdr_filt_lane1_u.bits.lane1_filt
typedef volatile struct rx_cdr_filt_lane1_s {
	union {
		struct {
			unsigned int lane1_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane1;
	} rx_cdr_filt_lane1_u;
} rx_cdr_filt_lane1_t;
#endif /* __RX_CDR_FILT_LANE1__ */

#ifndef __RX_CDR_FILT_LANE2__
#define __RX_CDR_FILT_LANE2__
#define RX_CDR_FILT_LANE2(x) (x)->rx_cdr_filt_lane2_register.rx_cdr_filt_lane2_u.rx_cdr_filt_lane2
#define rx_cdr_regs_LANE2_FILT(x) (x)->rx_cdr_filt_lane2_register.rx_cdr_filt_lane2_u.bits.lane2_filt
typedef volatile struct rx_cdr_filt_lane2_s {
	union {
		struct {
			unsigned int lane2_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane2;
	} rx_cdr_filt_lane2_u;
} rx_cdr_filt_lane2_t;
#endif /* __RX_CDR_FILT_LANE2__ */

#ifndef __RX_CDR_FILT_LANE3__
#define __RX_CDR_FILT_LANE3__
#define RX_CDR_FILT_LANE3(x) (x)->rx_cdr_filt_lane3_register.rx_cdr_filt_lane3_u.rx_cdr_filt_lane3
#define rx_cdr_regs_LANE3_FILT(x) (x)->rx_cdr_filt_lane3_register.rx_cdr_filt_lane3_u.bits.lane3_filt
typedef volatile struct rx_cdr_filt_lane3_s {
	union {
		struct {
			unsigned int lane3_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane3;
	} rx_cdr_filt_lane3_u;
} rx_cdr_filt_lane3_t;
#endif /* __RX_CDR_FILT_LANE3__ */

#ifndef __RX_CDR_FILT_LANE4__
#define __RX_CDR_FILT_LANE4__
#define RX_CDR_FILT_LANE4(x) (x)->rx_cdr_filt_lane4_register.rx_cdr_filt_lane4_u.rx_cdr_filt_lane4
#define rx_cdr_regs_LANE4_FILT(x) (x)->rx_cdr_filt_lane4_register.rx_cdr_filt_lane4_u.bits.lane4_filt
typedef volatile struct rx_cdr_filt_lane4_s {
	union {
		struct {
			unsigned int lane4_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane4;
	} rx_cdr_filt_lane4_u;
} rx_cdr_filt_lane4_t;
#endif /* __RX_CDR_FILT_LANE4__ */

#ifndef __RX_CDR_FILT_LANE5__
#define __RX_CDR_FILT_LANE5__
#define RX_CDR_FILT_LANE5(x) (x)->rx_cdr_filt_lane5_register.rx_cdr_filt_lane5_u.rx_cdr_filt_lane5
#define rx_cdr_regs_LANE5_FILT(x) (x)->rx_cdr_filt_lane5_register.rx_cdr_filt_lane5_u.bits.lane5_filt
typedef volatile struct rx_cdr_filt_lane5_s {
	union {
		struct {
			unsigned int lane5_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane5;
	} rx_cdr_filt_lane5_u;
} rx_cdr_filt_lane5_t;
#endif /* __RX_CDR_FILT_LANE5__ */

#ifndef __RX_CDR_FILT_LANE6__
#define __RX_CDR_FILT_LANE6__
#define RX_CDR_FILT_LANE6(x) (x)->rx_cdr_filt_lane6_register.rx_cdr_filt_lane6_u.rx_cdr_filt_lane6
#define rx_cdr_regs_LANE6_FILT(x) (x)->rx_cdr_filt_lane6_register.rx_cdr_filt_lane6_u.bits.lane6_filt
typedef volatile struct rx_cdr_filt_lane6_s {
	union {
		struct {
			unsigned int lane6_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane6;
	} rx_cdr_filt_lane6_u;
} rx_cdr_filt_lane6_t;
#endif /* __RX_CDR_FILT_LANE6__ */

#ifndef __RX_CDR_FILT_LANE7__
#define __RX_CDR_FILT_LANE7__
#define RX_CDR_FILT_LANE7(x) (x)->rx_cdr_filt_lane7_register.rx_cdr_filt_lane7_u.rx_cdr_filt_lane7
#define rx_cdr_regs_LANE7_FILT(x) (x)->rx_cdr_filt_lane7_register.rx_cdr_filt_lane7_u.bits.lane7_filt
typedef volatile struct rx_cdr_filt_lane7_s {
	union {
		struct {
			unsigned int lane7_filt : 18;
		} bits;
		uint32_t rx_cdr_filt_lane7;
	} rx_cdr_filt_lane7_u;
} rx_cdr_filt_lane7_t;
#endif /* __RX_CDR_FILT_LANE7__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE0__
#define __RX_CDR_FLEX_FIFO_STATE_LANE0__
#define RX_CDR_FLEX_FIFO_STATE_LANE0(x) (x)->rx_cdr_flex_fifo_state_lane0_register.rx_cdr_flex_fifo_state_lane0_u.rx_cdr_flex_fifo_state_lane0
#define rx_cdr_regs_LANE0_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane0_register.rx_cdr_flex_fifo_state_lane0_u.bits.lane0_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane0_s {
	union {
		struct {
			unsigned int lane0_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane0;
	} rx_cdr_flex_fifo_state_lane0_u;
} rx_cdr_flex_fifo_state_lane0_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE0__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE1__
#define __RX_CDR_FLEX_FIFO_STATE_LANE1__
#define RX_CDR_FLEX_FIFO_STATE_LANE1(x) (x)->rx_cdr_flex_fifo_state_lane1_register.rx_cdr_flex_fifo_state_lane1_u.rx_cdr_flex_fifo_state_lane1
#define rx_cdr_regs_LANE1_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane1_register.rx_cdr_flex_fifo_state_lane1_u.bits.lane1_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane1_s {
	union {
		struct {
			unsigned int lane1_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane1;
	} rx_cdr_flex_fifo_state_lane1_u;
} rx_cdr_flex_fifo_state_lane1_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE1__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE2__
#define __RX_CDR_FLEX_FIFO_STATE_LANE2__
#define RX_CDR_FLEX_FIFO_STATE_LANE2(x) (x)->rx_cdr_flex_fifo_state_lane2_register.rx_cdr_flex_fifo_state_lane2_u.rx_cdr_flex_fifo_state_lane2
#define rx_cdr_regs_LANE2_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane2_register.rx_cdr_flex_fifo_state_lane2_u.bits.lane2_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane2_s {
	union {
		struct {
			unsigned int lane2_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane2;
	} rx_cdr_flex_fifo_state_lane2_u;
} rx_cdr_flex_fifo_state_lane2_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE2__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE3__
#define __RX_CDR_FLEX_FIFO_STATE_LANE3__
#define RX_CDR_FLEX_FIFO_STATE_LANE3(x) (x)->rx_cdr_flex_fifo_state_lane3_register.rx_cdr_flex_fifo_state_lane3_u.rx_cdr_flex_fifo_state_lane3
#define rx_cdr_regs_LANE3_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane3_register.rx_cdr_flex_fifo_state_lane3_u.bits.lane3_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane3_s {
	union {
		struct {
			unsigned int lane3_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane3;
	} rx_cdr_flex_fifo_state_lane3_u;
} rx_cdr_flex_fifo_state_lane3_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE3__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE4__
#define __RX_CDR_FLEX_FIFO_STATE_LANE4__
#define RX_CDR_FLEX_FIFO_STATE_LANE4(x) (x)->rx_cdr_flex_fifo_state_lane4_register.rx_cdr_flex_fifo_state_lane4_u.rx_cdr_flex_fifo_state_lane4
#define rx_cdr_regs_LANE4_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane4_register.rx_cdr_flex_fifo_state_lane4_u.bits.lane4_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane4_s {
	union {
		struct {
			unsigned int lane4_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane4;
	} rx_cdr_flex_fifo_state_lane4_u;
} rx_cdr_flex_fifo_state_lane4_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE4__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE5__
#define __RX_CDR_FLEX_FIFO_STATE_LANE5__
#define RX_CDR_FLEX_FIFO_STATE_LANE5(x) (x)->rx_cdr_flex_fifo_state_lane5_register.rx_cdr_flex_fifo_state_lane5_u.rx_cdr_flex_fifo_state_lane5
#define rx_cdr_regs_LANE5_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane5_register.rx_cdr_flex_fifo_state_lane5_u.bits.lane5_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane5_s {
	union {
		struct {
			unsigned int lane5_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane5;
	} rx_cdr_flex_fifo_state_lane5_u;
} rx_cdr_flex_fifo_state_lane5_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE5__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE6__
#define __RX_CDR_FLEX_FIFO_STATE_LANE6__
#define RX_CDR_FLEX_FIFO_STATE_LANE6(x) (x)->rx_cdr_flex_fifo_state_lane6_register.rx_cdr_flex_fifo_state_lane6_u.rx_cdr_flex_fifo_state_lane6
#define rx_cdr_regs_LANE6_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane6_register.rx_cdr_flex_fifo_state_lane6_u.bits.lane6_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane6_s {
	union {
		struct {
			unsigned int lane6_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane6;
	} rx_cdr_flex_fifo_state_lane6_u;
} rx_cdr_flex_fifo_state_lane6_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE6__ */

#ifndef __RX_CDR_FLEX_FIFO_STATE_LANE7__
#define __RX_CDR_FLEX_FIFO_STATE_LANE7__
#define RX_CDR_FLEX_FIFO_STATE_LANE7(x) (x)->rx_cdr_flex_fifo_state_lane7_register.rx_cdr_flex_fifo_state_lane7_u.rx_cdr_flex_fifo_state_lane7
#define rx_cdr_regs_LANE7_FLEX_FIFO_STATE(x) (x)->rx_cdr_flex_fifo_state_lane7_register.rx_cdr_flex_fifo_state_lane7_u.bits.lane7_flex_fifo_state
typedef volatile struct rx_cdr_flex_fifo_state_lane7_s {
	union {
		struct {
			unsigned int lane7_flex_fifo_state : 4;
		} bits;
		uint32_t rx_cdr_flex_fifo_state_lane7;
	} rx_cdr_flex_fifo_state_lane7_u;
} rx_cdr_flex_fifo_state_lane7_t;
#endif /* __RX_CDR_FLEX_FIFO_STATE_LANE7__ */

#ifndef __RX_CDR_MODE__
#define __RX_CDR_MODE__
#define RX_CDR_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.rx_cdr_mode
#define rx_cdr_regs_LANE0_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane0_mode
#define rx_cdr_regs_LANE1_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane1_mode
#define rx_cdr_regs_LANE2_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane2_mode
#define rx_cdr_regs_LANE3_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane3_mode
#define rx_cdr_regs_LANE4_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane4_mode
#define rx_cdr_regs_LANE5_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane5_mode
#define rx_cdr_regs_LANE6_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane6_mode
#define rx_cdr_regs_LANE7_MODE(x) (x)->rx_cdr_mode_register.rx_cdr_mode_u.bits.lane7_mode
typedef volatile struct rx_cdr_mode_s {
	union {
		struct {
			unsigned int lane0_mode : 1;
			unsigned int lane1_mode : 1;
			unsigned int lane2_mode : 1;
			unsigned int lane3_mode : 1;
			unsigned int lane4_mode : 1;
			unsigned int lane5_mode : 1;
			unsigned int lane6_mode : 1;
			unsigned int lane7_mode : 1;
		} bits;
		uint32_t rx_cdr_mode;
	} rx_cdr_mode_u;
} rx_cdr_mode_t;
#endif /* __RX_CDR_MODE__ */

#ifndef __RX_CDR_SDR_MODE__
#define __RX_CDR_SDR_MODE__
#define RX_CDR_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.rx_cdr_sdr_mode
#define rx_cdr_regs_LANE0_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane0_sdr_mode
#define rx_cdr_regs_LANE1_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane1_sdr_mode
#define rx_cdr_regs_LANE2_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane2_sdr_mode
#define rx_cdr_regs_LANE3_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane3_sdr_mode
#define rx_cdr_regs_LANE4_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane4_sdr_mode
#define rx_cdr_regs_LANE5_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane5_sdr_mode
#define rx_cdr_regs_LANE6_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane6_sdr_mode
#define rx_cdr_regs_LANE7_SDR_MODE(x) (x)->rx_cdr_sdr_mode_register.rx_cdr_sdr_mode_u.bits.lane7_sdr_mode
typedef volatile struct rx_cdr_sdr_mode_s {
	union {
		struct {
			unsigned int lane0_sdr_mode : 1;
			unsigned int lane1_sdr_mode : 1;
			unsigned int lane2_sdr_mode : 1;
			unsigned int lane3_sdr_mode : 1;
			unsigned int lane4_sdr_mode : 1;
			unsigned int lane5_sdr_mode : 1;
			unsigned int lane6_sdr_mode : 1;
			unsigned int lane7_sdr_mode : 1;
		} bits;
		uint32_t rx_cdr_sdr_mode;
	} rx_cdr_sdr_mode_u;
} rx_cdr_sdr_mode_t;
#endif /* __RX_CDR_SDR_MODE__ */

#ifndef __RX_CDR_AMP_BIAS_LANE0__
#define __RX_CDR_AMP_BIAS_LANE0__
#define RX_CDR_AMP_BIAS_LANE0(x) (x)->rx_cdr_amp_bias_lane0_register.rx_cdr_amp_bias_lane0_u.rx_cdr_amp_bias_lane0
#define rx_cdr_regs_LANE0_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane0_register.rx_cdr_amp_bias_lane0_u.bits.lane0_ctrl_amp_int
#define rx_cdr_regs_LANE0_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane0_register.rx_cdr_amp_bias_lane0_u.bits.lane0_ctrl_term_ext
#define rx_cdr_regs_LANE0_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane0_register.rx_cdr_amp_bias_lane0_u.bits.lane0_ctrl_term_int
#define rx_cdr_regs_LANE0_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane0_register.rx_cdr_amp_bias_lane0_u.bits.lane0_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane0_s {
	union {
		struct {
			unsigned int lane0_ctrl_amp_int : 3;
			unsigned int lane0_ctrl_term_ext : 3;
			unsigned int lane0_ctrl_term_int : 3;
			unsigned int lane0_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane0;
	} rx_cdr_amp_bias_lane0_u;
} rx_cdr_amp_bias_lane0_t;
#endif /* __RX_CDR_AMP_BIAS_LANE0__ */

#ifndef __RX_CDR_AMP_BIAS_LANE1__
#define __RX_CDR_AMP_BIAS_LANE1__
#define RX_CDR_AMP_BIAS_LANE1(x) (x)->rx_cdr_amp_bias_lane1_register.rx_cdr_amp_bias_lane1_u.rx_cdr_amp_bias_lane1
#define rx_cdr_regs_LANE1_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane1_register.rx_cdr_amp_bias_lane1_u.bits.lane1_ctrl_amp_int
#define rx_cdr_regs_LANE1_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane1_register.rx_cdr_amp_bias_lane1_u.bits.lane1_ctrl_term_ext
#define rx_cdr_regs_LANE1_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane1_register.rx_cdr_amp_bias_lane1_u.bits.lane1_ctrl_term_int
#define rx_cdr_regs_LANE1_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane1_register.rx_cdr_amp_bias_lane1_u.bits.lane1_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane1_s {
	union {
		struct {
			unsigned int lane1_ctrl_amp_int : 3;
			unsigned int lane1_ctrl_term_ext : 3;
			unsigned int lane1_ctrl_term_int : 3;
			unsigned int lane1_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane1;
	} rx_cdr_amp_bias_lane1_u;
} rx_cdr_amp_bias_lane1_t;
#endif /* __RX_CDR_AMP_BIAS_LANE1__ */

#ifndef __RX_CDR_AMP_BIAS_LANE2__
#define __RX_CDR_AMP_BIAS_LANE2__
#define RX_CDR_AMP_BIAS_LANE2(x) (x)->rx_cdr_amp_bias_lane2_register.rx_cdr_amp_bias_lane2_u.rx_cdr_amp_bias_lane2
#define rx_cdr_regs_LANE2_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane2_register.rx_cdr_amp_bias_lane2_u.bits.lane2_ctrl_amp_int
#define rx_cdr_regs_LANE2_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane2_register.rx_cdr_amp_bias_lane2_u.bits.lane2_ctrl_term_ext
#define rx_cdr_regs_LANE2_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane2_register.rx_cdr_amp_bias_lane2_u.bits.lane2_ctrl_term_int
#define rx_cdr_regs_LANE2_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane2_register.rx_cdr_amp_bias_lane2_u.bits.lane2_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane2_s {
	union {
		struct {
			unsigned int lane2_ctrl_amp_int : 3;
			unsigned int lane2_ctrl_term_ext : 3;
			unsigned int lane2_ctrl_term_int : 3;
			unsigned int lane2_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane2;
	} rx_cdr_amp_bias_lane2_u;
} rx_cdr_amp_bias_lane2_t;
#endif /* __RX_CDR_AMP_BIAS_LANE2__ */

#ifndef __RX_CDR_AMP_BIAS_LANE3__
#define __RX_CDR_AMP_BIAS_LANE3__
#define RX_CDR_AMP_BIAS_LANE3(x) (x)->rx_cdr_amp_bias_lane3_register.rx_cdr_amp_bias_lane3_u.rx_cdr_amp_bias_lane3
#define rx_cdr_regs_LANE3_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane3_register.rx_cdr_amp_bias_lane3_u.bits.lane3_ctrl_amp_int
#define rx_cdr_regs_LANE3_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane3_register.rx_cdr_amp_bias_lane3_u.bits.lane3_ctrl_term_ext
#define rx_cdr_regs_LANE3_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane3_register.rx_cdr_amp_bias_lane3_u.bits.lane3_ctrl_term_int
#define rx_cdr_regs_LANE3_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane3_register.rx_cdr_amp_bias_lane3_u.bits.lane3_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane3_s {
	union {
		struct {
			unsigned int lane3_ctrl_amp_int : 3;
			unsigned int lane3_ctrl_term_ext : 3;
			unsigned int lane3_ctrl_term_int : 3;
			unsigned int lane3_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane3;
	} rx_cdr_amp_bias_lane3_u;
} rx_cdr_amp_bias_lane3_t;
#endif /* __RX_CDR_AMP_BIAS_LANE3__ */

#ifndef __RX_CDR_AMP_BIAS_LANE4__
#define __RX_CDR_AMP_BIAS_LANE4__
#define RX_CDR_AMP_BIAS_LANE4(x) (x)->rx_cdr_amp_bias_lane4_register.rx_cdr_amp_bias_lane4_u.rx_cdr_amp_bias_lane4
#define rx_cdr_regs_LANE4_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane4_register.rx_cdr_amp_bias_lane4_u.bits.lane4_ctrl_amp_int
#define rx_cdr_regs_LANE4_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane4_register.rx_cdr_amp_bias_lane4_u.bits.lane4_ctrl_term_ext
#define rx_cdr_regs_LANE4_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane4_register.rx_cdr_amp_bias_lane4_u.bits.lane4_ctrl_term_int
#define rx_cdr_regs_LANE4_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane4_register.rx_cdr_amp_bias_lane4_u.bits.lane4_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane4_s {
	union {
		struct {
			unsigned int lane4_ctrl_amp_int : 3;
			unsigned int lane4_ctrl_term_ext : 3;
			unsigned int lane4_ctrl_term_int : 3;
			unsigned int lane4_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane4;
	} rx_cdr_amp_bias_lane4_u;
} rx_cdr_amp_bias_lane4_t;
#endif /* __RX_CDR_AMP_BIAS_LANE4__ */

#ifndef __RX_CDR_AMP_BIAS_LANE5__
#define __RX_CDR_AMP_BIAS_LANE5__
#define RX_CDR_AMP_BIAS_LANE5(x) (x)->rx_cdr_amp_bias_lane5_register.rx_cdr_amp_bias_lane5_u.rx_cdr_amp_bias_lane5
#define rx_cdr_regs_LANE5_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane5_register.rx_cdr_amp_bias_lane5_u.bits.lane5_ctrl_amp_int
#define rx_cdr_regs_LANE5_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane5_register.rx_cdr_amp_bias_lane5_u.bits.lane5_ctrl_term_ext
#define rx_cdr_regs_LANE5_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane5_register.rx_cdr_amp_bias_lane5_u.bits.lane5_ctrl_term_int
#define rx_cdr_regs_LANE5_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane5_register.rx_cdr_amp_bias_lane5_u.bits.lane5_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane5_s {
	union {
		struct {
			unsigned int lane5_ctrl_amp_int : 3;
			unsigned int lane5_ctrl_term_ext : 3;
			unsigned int lane5_ctrl_term_int : 3;
			unsigned int lane5_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane5;
	} rx_cdr_amp_bias_lane5_u;
} rx_cdr_amp_bias_lane5_t;
#endif /* __RX_CDR_AMP_BIAS_LANE5__ */

#ifndef __RX_CDR_AMP_BIAS_LANE6__
#define __RX_CDR_AMP_BIAS_LANE6__
#define RX_CDR_AMP_BIAS_LANE6(x) (x)->rx_cdr_amp_bias_lane6_register.rx_cdr_amp_bias_lane6_u.rx_cdr_amp_bias_lane6
#define rx_cdr_regs_LANE6_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane6_register.rx_cdr_amp_bias_lane6_u.bits.lane6_ctrl_amp_int
#define rx_cdr_regs_LANE6_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane6_register.rx_cdr_amp_bias_lane6_u.bits.lane6_ctrl_term_ext
#define rx_cdr_regs_LANE6_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane6_register.rx_cdr_amp_bias_lane6_u.bits.lane6_ctrl_term_int
#define rx_cdr_regs_LANE6_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane6_register.rx_cdr_amp_bias_lane6_u.bits.lane6_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane6_s {
	union {
		struct {
			unsigned int lane6_ctrl_amp_int : 3;
			unsigned int lane6_ctrl_term_ext : 3;
			unsigned int lane6_ctrl_term_int : 3;
			unsigned int lane6_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane6;
	} rx_cdr_amp_bias_lane6_u;
} rx_cdr_amp_bias_lane6_t;
#endif /* __RX_CDR_AMP_BIAS_LANE6__ */

#ifndef __RX_CDR_AMP_BIAS_LANE7__
#define __RX_CDR_AMP_BIAS_LANE7__
#define RX_CDR_AMP_BIAS_LANE7(x) (x)->rx_cdr_amp_bias_lane7_register.rx_cdr_amp_bias_lane7_u.rx_cdr_amp_bias_lane7
#define rx_cdr_regs_LANE7_CTRL_AMP_INT(x) (x)->rx_cdr_amp_bias_lane7_register.rx_cdr_amp_bias_lane7_u.bits.lane7_ctrl_amp_int
#define rx_cdr_regs_LANE7_CTRL_TERM_EXT(x) (x)->rx_cdr_amp_bias_lane7_register.rx_cdr_amp_bias_lane7_u.bits.lane7_ctrl_term_ext
#define rx_cdr_regs_LANE7_CTRL_TERM_INT(x) (x)->rx_cdr_amp_bias_lane7_register.rx_cdr_amp_bias_lane7_u.bits.lane7_ctrl_term_int
#define rx_cdr_regs_LANE7_SEL_2V5(x) (x)->rx_cdr_amp_bias_lane7_register.rx_cdr_amp_bias_lane7_u.bits.lane7_sel_2v5
typedef volatile struct rx_cdr_amp_bias_lane7_s {
	union {
		struct {
			unsigned int lane7_ctrl_amp_int : 3;
			unsigned int lane7_ctrl_term_ext : 3;
			unsigned int lane7_ctrl_term_int : 3;
			unsigned int lane7_sel_2v5 : 1;
		} bits;
		uint32_t rx_cdr_amp_bias_lane7;
	} rx_cdr_amp_bias_lane7_u;
} rx_cdr_amp_bias_lane7_t;
#endif /* __RX_CDR_AMP_BIAS_LANE7__ */

#ifndef __RX_CDR_LANE_EN__
#define __RX_CDR_LANE_EN__
#define RX_CDR_LANE_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.rx_cdr_lane_en
#define rx_cdr_regs_LANE0_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane0_en
#define rx_cdr_regs_LANE1_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane1_en
#define rx_cdr_regs_LANE2_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane2_en
#define rx_cdr_regs_LANE3_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane3_en
#define rx_cdr_regs_LANE4_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane4_en
#define rx_cdr_regs_LANE5_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane5_en
#define rx_cdr_regs_LANE6_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane6_en
#define rx_cdr_regs_LANE7_EN(x) (x)->rx_cdr_lane_en_register.rx_cdr_lane_en_u.bits.lane7_en
typedef volatile struct rx_cdr_lane_en_s {
	union {
		struct {
			unsigned int lane0_en : 1;
			unsigned int lane1_en : 1;
			unsigned int lane2_en : 1;
			unsigned int lane3_en : 1;
			unsigned int lane4_en : 1;
			unsigned int lane5_en : 1;
			unsigned int lane6_en : 1;
			unsigned int lane7_en : 1;
		} bits;
		uint32_t rx_cdr_lane_en;
	} rx_cdr_lane_en_u;
} rx_cdr_lane_en_t;
#endif /* __RX_CDR_LANE_EN__ */

typedef struct rx_cdr_regs_s
{
	uint32_t dummy0_register;
	rx_cdr_reset_ctrl_t rx_cdr_reset_ctrl_register;	// Address: 0x1
	rx_cdr_clk_polarity_t rx_cdr_clk_polarity_register;	// Address: 0x2
	rx_cdr_hfboost_lane0_t rx_cdr_hfboost_lane0_register;	// Address: 0x3
	rx_cdr_hfboost_lane1_t rx_cdr_hfboost_lane1_register;	// Address: 0x4
	rx_cdr_hfboost_lane2_t rx_cdr_hfboost_lane2_register;	// Address: 0x5
	rx_cdr_hfboost_lane3_t rx_cdr_hfboost_lane3_register;	// Address: 0x6
	rx_cdr_hfboost_lane4_t rx_cdr_hfboost_lane4_register;	// Address: 0x7
	rx_cdr_hfboost_lane5_t rx_cdr_hfboost_lane5_register;	// Address: 0x8
	rx_cdr_hfboost_lane6_t rx_cdr_hfboost_lane6_register;	// Address: 0x9
	rx_cdr_hfboost_lane7_t rx_cdr_hfboost_lane7_register;	// Address: 0xa
	rx_cdr_pd_lane0_t rx_cdr_pd_lane0_register;	// Address: 0xb
	rx_cdr_pd_lane1_t rx_cdr_pd_lane1_register;	// Address: 0xc
	rx_cdr_pd_lane2_t rx_cdr_pd_lane2_register;	// Address: 0xd
	rx_cdr_pd_lane3_t rx_cdr_pd_lane3_register;	// Address: 0xe
	rx_cdr_pd_lane4_t rx_cdr_pd_lane4_register;	// Address: 0xf
	rx_cdr_pd_lane5_t rx_cdr_pd_lane5_register;	// Address: 0x10
	rx_cdr_pd_lane6_t rx_cdr_pd_lane6_register;	// Address: 0x11
	rx_cdr_pd_lane7_t rx_cdr_pd_lane7_register;	// Address: 0x12
	rx_cdr_filt_lane0_t rx_cdr_filt_lane0_register;	// Address: 0x13
	rx_cdr_filt_lane1_t rx_cdr_filt_lane1_register;	// Address: 0x14
	rx_cdr_filt_lane2_t rx_cdr_filt_lane2_register;	// Address: 0x15
	rx_cdr_filt_lane3_t rx_cdr_filt_lane3_register;	// Address: 0x16
	rx_cdr_filt_lane4_t rx_cdr_filt_lane4_register;	// Address: 0x17
	rx_cdr_filt_lane5_t rx_cdr_filt_lane5_register;	// Address: 0x18
	rx_cdr_filt_lane6_t rx_cdr_filt_lane6_register;	// Address: 0x19
	rx_cdr_filt_lane7_t rx_cdr_filt_lane7_register;	// Address: 0x1a
	rx_cdr_flex_fifo_state_lane0_t rx_cdr_flex_fifo_state_lane0_register;	// Address: 0x1b
	rx_cdr_flex_fifo_state_lane1_t rx_cdr_flex_fifo_state_lane1_register;	// Address: 0x1c
	rx_cdr_flex_fifo_state_lane2_t rx_cdr_flex_fifo_state_lane2_register;	// Address: 0x1d
	rx_cdr_flex_fifo_state_lane3_t rx_cdr_flex_fifo_state_lane3_register;	// Address: 0x1e
	rx_cdr_flex_fifo_state_lane4_t rx_cdr_flex_fifo_state_lane4_register;	// Address: 0x1f
	rx_cdr_flex_fifo_state_lane5_t rx_cdr_flex_fifo_state_lane5_register;	// Address: 0x20
	rx_cdr_flex_fifo_state_lane6_t rx_cdr_flex_fifo_state_lane6_register;	// Address: 0x21
	rx_cdr_flex_fifo_state_lane7_t rx_cdr_flex_fifo_state_lane7_register;	// Address: 0x22
	rx_cdr_mode_t rx_cdr_mode_register;	// Address: 0x23
	rx_cdr_sdr_mode_t rx_cdr_sdr_mode_register;	// Address: 0x24
	rx_cdr_amp_bias_lane0_t rx_cdr_amp_bias_lane0_register;	// Address: 0x25
	rx_cdr_amp_bias_lane1_t rx_cdr_amp_bias_lane1_register;	// Address: 0x26
	rx_cdr_amp_bias_lane2_t rx_cdr_amp_bias_lane2_register;	// Address: 0x27
	rx_cdr_amp_bias_lane3_t rx_cdr_amp_bias_lane3_register;	// Address: 0x28
	rx_cdr_amp_bias_lane4_t rx_cdr_amp_bias_lane4_register;	// Address: 0x29
	rx_cdr_amp_bias_lane5_t rx_cdr_amp_bias_lane5_register;	// Address: 0x2a
	rx_cdr_amp_bias_lane6_t rx_cdr_amp_bias_lane6_register;	// Address: 0x2b
	rx_cdr_amp_bias_lane7_t rx_cdr_amp_bias_lane7_register;	// Address: 0x2c
	rx_cdr_lane_en_t rx_cdr_lane_en_register;	// Address: 0x2d
} rx_cdr_regs_t;

#endif /* __RX_CDR_REGS__ */
