//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_FRAMER5_HXX__
#define __RX_FRAMER5_HXX__

#define RX_FRAMER5_RX_LANE_FRAMER_CONTROL                     (REG_RX_FRAMER5+0x0)
#define RX_FRAMER5_RX_LANE_AND_FRAMER_FIFO_STATUS             (REG_RX_FRAMER5+0x4)
#define RX_FRAMER5_OOBREG_RDDATA_LANE_DATA_FIFO_SHIFT_ERRORS  (REG_RX_FRAMER5+0x8)
#define RX_FRAMER5_DAC_TEST_SAMP                              (REG_RX_FRAMER5+0xc)

#endif /* __RX_FRAMER5_HXX__ */
