//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_LL_CORE_HXX__
#define __RX_LL_CORE_HXX__

#define RX_LL_CORE_RX_LINK_CONFIG                (REG_RX_LL_CORE+0x0)
#define RX_LL_CORE_RX_LINK_ENABLE                (REG_RX_LL_CORE+0x4)
#define RX_LL_CORE_RX_COMMA_CONFIG               (REG_RX_LL_CORE+0x8)
#define RX_LL_CORE_RX_ALIGN_CONFIG               (REG_RX_LL_CORE+0xc)
#define RX_LL_CORE_RX_CGS_CONFIG                 (REG_RX_LL_CORE+0x10)
#define RX_LL_CORE_RX_SYSREF_MISALIGN_COUNT      (REG_RX_LL_CORE+0x14)
#define RX_LL_CORE_RX_LANE_ENABLE                (REG_RX_LL_CORE+0x18)
#define RX_LL_CORE_RX_ILAS_CONFIG                (REG_RX_LL_CORE+0x1c)
#define RX_LL_CORE_RX_SCRAMBLE_CONFIG            (REG_RX_LL_CORE+0x20)
#define RX_LL_CORE_RX_OUT_TIMING                 (REG_RX_LL_CORE+0x24)
#define RX_LL_CORE_RX_TRANSPORT_CONFIG           (REG_RX_LL_CORE+0x28)
#define RX_LL_CORE_RX_DEBUG                      (REG_RX_LL_CORE+0x2c)
#define RX_LL_CORE_RX_FCLK_AND_LINKLAYER_STATUS  (REG_RX_LL_CORE+0x30)
#define RX_LL_CORE_RX_D21_5_THRESHOLD            (REG_RX_LL_CORE+0x34)
#define RX_LL_CORE_PHY_ATEST_CTRL                (REG_RX_LL_CORE+0x38)
#define RX_LL_CORE_RX_GP                         (REG_RX_LL_CORE+0x3c)
#define RX_LL_CORE_DLL1_ATEST_CTRL               (REG_RX_LL_CORE+0x40)
#define RX_LL_CORE_DLL_CTRL_REGS                 (REG_RX_LL_CORE+0x44)
#define RX_LL_CORE_DLL_CPPFD_CTRL_REGS           (REG_RX_LL_CORE+0x48)
#define RX_LL_CORE_DLL_VCDL_DLY_REGS             (REG_RX_LL_CORE+0x4c)
#define RX_LL_CORE_DLL_DUTY_CYL_REGS             (REG_RX_LL_CORE+0x50)
#define RX_LL_CORE_DLL_RSTN_REGS                 (REG_RX_LL_CORE+0x54)
#define RX_LL_CORE_DLL_GP                        (REG_RX_LL_CORE+0x58)
#define RX_LL_CORE_DLL_LOCK_DETECT               (REG_RX_LL_CORE+0x5c)

#endif /* __RX_LL_CORE_HXX__ */
