//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_LL_LANE5_HXX__
#define __RX_LL_LANE5_HXX__

#define RX_LL_LANE5_RX_LANE_CGS_STATUS      (REG_RX_LL_LANE5+0x0)
#define RX_LL_LANE5_RX_LANE_COUNTS          (REG_RX_LL_LANE5+0x4)
#define RX_LL_LANE5_RX_LANE_CONFIG          (REG_RX_LL_LANE5+0x8)
#define RX_LL_LANE5_RX_TOTAL_ERRORS         (REG_RX_LL_LANE5+0xc)
#define RX_LL_LANE5_RX_ILAS_STATUS          (REG_RX_LL_LANE5+0x10)
#define RX_LL_LANE5_RX_MANUAL_CONTROL       (REG_RX_LL_LANE5+0x14)
#define RX_LL_LANE5_RX_LANE_D21_5_COUNTS    (REG_RX_LL_LANE5+0x18)
#define RX_LL_LANE5_RX_LANE_NON_K_CNT4TEST  (REG_RX_LL_LANE5+0x1c)
#define RX_LL_LANE5_SERDES_20B_PIPELINE     (REG_RX_LL_LANE5+0x20)
#define RX_LL_LANE5_RX_CONFIG0_DATA         (REG_RX_LL_LANE5+0x24)
#define RX_LL_LANE5_RX_CONFIG1_DATA         (REG_RX_LL_LANE5+0x28)
#define RX_LL_LANE5_RX_CONFIG2_DATA         (REG_RX_LL_LANE5+0x2c)
#define RX_LL_LANE5_RX_CONFIG3_DATA         (REG_RX_LL_LANE5+0x30)
#define RX_LL_LANE5_RX_CONFIG4_DATA         (REG_RX_LL_LANE5+0x34)
#define RX_LL_LANE5_RX_CONFIG5_DATA         (REG_RX_LL_LANE5+0x38)
#define RX_LL_LANE5_RX_CONFIG6_DATA         (REG_RX_LL_LANE5+0x3c)

#endif /* __RX_LL_LANE5_HXX__ */
