//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __RX_MERLIN_CTRL6_HXX__
#define __RX_MERLIN_CTRL6_HXX__

#define RX_MERLIN_CTRL6_FRAMER_CONTROLLER_CONTROL       (REG_RX_MERLIN_CTRL6+0x0)
#define RX_MERLIN_CTRL6_FRAMER_CONTROLLER_STATUS        (REG_RX_MERLIN_CTRL6+0x4)
#define RX_MERLIN_CTRL6_TRIGGER_CONTROL                 (REG_RX_MERLIN_CTRL6+0x8)
#define RX_MERLIN_CTRL6_WR_MICROCODE_REG_2              (REG_RX_MERLIN_CTRL6+0xc)
#define RX_MERLIN_CTRL6_WR_MICROCODE_REG_1              (REG_RX_MERLIN_CTRL6+0x10)
#define RX_MERLIN_CTRL6_WR_MICROCODE_REG_0              (REG_RX_MERLIN_CTRL6+0x14)
#define RX_MERLIN_CTRL6_MICROCODE_SRAM_BYTE_WRITE_MASK  (REG_RX_MERLIN_CTRL6+0x18)
#define RX_MERLIN_CTRL6_MICROCODE_SRAM_CONTROL          (REG_RX_MERLIN_CTRL6+0x1c)
#define RX_MERLIN_CTRL6_WAIT_NOP_REGISTERS              (REG_RX_MERLIN_CTRL6+0x20)
#define RX_MERLIN_CTRL6_DEBUG_CONTROL                   (REG_RX_MERLIN_CTRL6+0x24)
#define RX_MERLIN_CTRL6_DEBUG_DATA                      (REG_RX_MERLIN_CTRL6+0x28)
#define RX_MERLIN_CTRL6_SELF_CLEARING                   (REG_RX_MERLIN_CTRL6+0x2c)

#endif /* __RX_MERLIN_CTRL6_HXX__ */
