//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TEST_DSP1_MEM_PLAY_HXX__
#define __TEST_DSP1_MEM_PLAY_HXX__

#define TEST_DSP1_MEM_PLAY_CAPTURE_PLAYBACK_CONTROL        (REG_TEST_DSP1_MEM_PLAY+0x0)
#define TEST_DSP1_MEM_PLAY_CAPTURE_PLAYBACK_STATUS         (REG_TEST_DSP1_MEM_PLAY+0x4)
#define TEST_DSP1_MEM_PLAY_START_CAPTURE_PLAYBACK_ADDRESS  (REG_TEST_DSP1_MEM_PLAY+0x8)
#define TEST_DSP1_MEM_PLAY_BYTE_WRITE_MASK                 (REG_TEST_DSP1_MEM_PLAY+0xc)
#define TEST_DSP1_MEM_PLAY_CEN_MASK                        (REG_TEST_DSP1_MEM_PLAY+0x10)
#define TEST_DSP1_MEM_PLAY_AXI_BUS_MUX_Q                   (REG_TEST_DSP1_MEM_PLAY+0x14)
#define TEST_DSP1_MEM_PLAY_SHARED_SRAM_CONTROL             (REG_TEST_DSP1_MEM_PLAY+0x18)
#define TEST_DSP1_MEM_PLAY_SRAM_1_CONTROL                  (REG_TEST_DSP1_MEM_PLAY+0x1c)
#define TEST_DSP1_MEM_PLAY_SRAM_0_CONTROL                  (REG_TEST_DSP1_MEM_PLAY+0x20)
#define TEST_DSP1_MEM_PLAY_INITIATE_CAPTURE_CONTROL        (REG_TEST_DSP1_MEM_PLAY+0x24)
#define TEST_DSP1_MEM_PLAY_INITIATE_PLAYBACK_CONTROL       (REG_TEST_DSP1_MEM_PLAY+0x28)

#endif /* __TEST_DSP1_MEM_PLAY_HXX__ */
