//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TX_DRV_HXX__
#define __TX_DRV_HXX__

#define TX_DRV_TX_P2S_RESET_CTRL     (REG_TX_DRV+0x0)
#define TX_DRV_TX_P2S_MODE_CTRL      (REG_TX_DRV+0x4)
#define TX_DRV_TX_P2S_LOAD_SDR       (REG_TX_DRV+0x8)
#define TX_DRV_TX_P2S_LOAD_DDR       (REG_TX_DRV+0xc)
#define TX_DRV_TX_P2S_LANE0_CTRL     (REG_TX_DRV+0x10)
#define TX_DRV_TX_P2S_LANE1_CTRL     (REG_TX_DRV+0x14)
#define TX_DRV_TX_P2S_LANE2_CTRL     (REG_TX_DRV+0x18)
#define TX_DRV_TX_P2S_LANE3_CTRL     (REG_TX_DRV+0x1c)
#define TX_DRV_TX_P2S_LANE4_CTRL     (REG_TX_DRV+0x20)
#define TX_DRV_TX_P2S_LANE5_CTRL     (REG_TX_DRV+0x24)
#define TX_DRV_TX_P2S_LANE6_CTRL     (REG_TX_DRV+0x28)
#define TX_DRV_TX_P2S_LANE7_CTRL     (REG_TX_DRV+0x2c)
#define TX_DRV_TX_P2S_DTEST          (REG_TX_DRV+0x30)
#define TX_DRV_TX_P2S_PPTEST         (REG_TX_DRV+0x34)
#define TX_DRV_TX_P2S_PMTEST         (REG_TX_DRV+0x38)
#define TX_DRV_TX_ZCAL_CTRL          (REG_TX_DRV+0x3c)
#define TX_DRV_TX_ZCAL_FREEZE        (REG_TX_DRV+0x40)
#define TX_DRV_TX_ZCAL_OFFSET        (REG_TX_DRV+0x44)
#define TX_DRV_TX_ZCAL_LANE0_OFFSET  (REG_TX_DRV+0x48)
#define TX_DRV_TX_ZCAL_LANE1_OFFSET  (REG_TX_DRV+0x4c)
#define TX_DRV_TX_ZCAL_LANE2_OFFSET  (REG_TX_DRV+0x50)
#define TX_DRV_TX_ZCAL_LANE3_OFFSET  (REG_TX_DRV+0x54)
#define TX_DRV_TX_ZCAL_LANE4_OFFSET  (REG_TX_DRV+0x58)
#define TX_DRV_TX_ZCAL_LANE5_OFFSET  (REG_TX_DRV+0x5c)
#define TX_DRV_TX_ZCAL_LANE6_OFFSET  (REG_TX_DRV+0x60)
#define TX_DRV_TX_ZCAL_LANE7_OFFSET  (REG_TX_DRV+0x64)
#define TX_DRV_TX_ZCAL_TEST          (REG_TX_DRV+0x68)
#define TX_DRV_TX_ZCAL_STATUS        (REG_TX_DRV+0x6c)
#define TX_DRV_TX_TXC_CTRL           (REG_TX_DRV+0x70)

#endif /* __TX_DRV_HXX__ */
