//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TX_FRAMER3_HXX__
#define __TX_FRAMER3_HXX__

#define TX_FRAMER3_TX_LANE_FRAMER_CONTROL     (REG_TX_FRAMER3+0x0)
#define TX_FRAMER3_LANE_FIFO_STATUS_REGISTER  (REG_TX_FRAMER3+0x4)

#endif /* __TX_FRAMER3_HXX__ */
