//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TX_LL_LANE3_HXX__
#define __TX_LL_LANE3_HXX__

#define TX_LL_LANE3_TX_LANE_CGS_ILAS_STATUS  (REG_TX_LL_LANE3+0x0)
#define TX_LL_LANE3_TX_LANE_CONFIG           (REG_TX_LL_LANE3+0x4)
#define TX_LL_LANE3_TX_MANUAL                (REG_TX_LL_LANE3+0x8)
#define TX_LL_LANE3_TX_TEST_MODES            (REG_TX_LL_LANE3+0xc)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_6    (REG_TX_LL_LANE3+0x10)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_5    (REG_TX_LL_LANE3+0x14)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_4    (REG_TX_LL_LANE3+0x18)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_3    (REG_TX_LL_LANE3+0x1c)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_2    (REG_TX_LL_LANE3+0x20)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_1    (REG_TX_LL_LANE3+0x24)
#define TX_LL_LANE3_TX_CONFIG_DATA_WORD_0    (REG_TX_LL_LANE3+0x28)
#define TX_LL_LANE3_ENCODER_TEST_INPUTS      (REG_TX_LL_LANE3+0x2c)
#define TX_LL_LANE3_ENCODER_TEST_OUTPUTS     (REG_TX_LL_LANE3+0x30)
#define TX_LL_LANE3_ENCODER_DATA_OUTPUTS     (REG_TX_LL_LANE3+0x34)

#endif /* __TX_LL_LANE3_HXX__ */
