//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TX_MERLIN_CTRL2_HXX__
#define __TX_MERLIN_CTRL2_HXX__

#define TX_MERLIN_CTRL2_FRAMER_CONTROLLER_CONTROL       (REG_TX_MERLIN_CTRL2+0x0)
#define TX_MERLIN_CTRL2_FRAMER_CONTROLLER_STATUS        (REG_TX_MERLIN_CTRL2+0x4)
#define TX_MERLIN_CTRL2_TRIGGER_CONTROL                 (REG_TX_MERLIN_CTRL2+0x8)
#define TX_MERLIN_CTRL2_WR_MICROCODE_REG_2              (REG_TX_MERLIN_CTRL2+0xc)
#define TX_MERLIN_CTRL2_WR_MICROCODE_REG_1              (REG_TX_MERLIN_CTRL2+0x10)
#define TX_MERLIN_CTRL2_WR_MICROCODE_REG_0              (REG_TX_MERLIN_CTRL2+0x14)
#define TX_MERLIN_CTRL2_MICROCODE_SRAM_BYTE_WRITE_MASK  (REG_TX_MERLIN_CTRL2+0x18)
#define TX_MERLIN_CTRL2_MICROCODE_SRAM_CONTROL          (REG_TX_MERLIN_CTRL2+0x1c)
#define TX_MERLIN_CTRL2_WAIT_NOP_REGISTERS              (REG_TX_MERLIN_CTRL2+0x20)
#define TX_MERLIN_CTRL2_DEBUG_CONTROL                   (REG_TX_MERLIN_CTRL2+0x24)
#define TX_MERLIN_CTRL2_DEBUG_DATA                      (REG_TX_MERLIN_CTRL2+0x28)
#define TX_MERLIN_CTRL2_SELF_CLEARING                   (REG_TX_MERLIN_CTRL2+0x2c)

#endif /* __TX_MERLIN_CTRL2_HXX__ */
