//*******************************************************************************
//      __  __                                                                  *
//     /  \/  \                                                                 *
//         \   \                                                                *
//    I Q - A N A L O G                                                         *
//           \   \            IQ-Analog Corp                                    *
//            \__/\__/       www.iqanalog.com                                   *
//                                                                              *
//------------------------------------------------------------------------------*
//                                                                              *
// Copyright (C) 2018-2019 IQ-Analog Corp. All rights reserved.                 *
//                                                                              *
//------------------------------------------------------------------------------*
// IQ-Analog CONFIDENTIAL                                                       *
//------------------------------------------------------------------------------*
//                                                                              *
// This file is released with "Government Purpose Rights" as defined            *
// in DFARS SUBPART 227.71, clause 252.227-7013.                                *
//                                                                              *
//*******************************************************************************

// Generated by RMM 3.3
// IQ-Analog Corp. 2013-2018.

#ifndef __TX_SAT_HXX__
#define __TX_SAT_HXX__

#define TX_SAT_ADC_SAT_LANE1_INIT_MASK    (REG_TX_SAT+0x0)
#define TX_SAT_ADC_SAT_LANE2_INIT_MASK    (REG_TX_SAT+0x4)
#define TX_SAT_ADC_SAT_LANE3_INIT_MASK    (REG_TX_SAT+0x8)
#define TX_SAT_ADC_SAT_LANE4_INIT_MASK    (REG_TX_SAT+0xc)
#define TX_SAT_ADC_SAT_LANE5_INIT_MASK    (REG_TX_SAT+0x10)
#define TX_SAT_ADC_SAT_LANE6_INIT_MASK    (REG_TX_SAT+0x14)
#define TX_SAT_ADC_SAT_LANE7_INIT_MASK    (REG_TX_SAT+0x18)
#define TX_SAT_ADC_SAT_LANE8_INIT_MASK    (REG_TX_SAT+0x1c)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_1  (REG_TX_SAT+0x20)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_2  (REG_TX_SAT+0x24)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_3  (REG_TX_SAT+0x28)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_4  (REG_TX_SAT+0x2c)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_5  (REG_TX_SAT+0x30)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_6  (REG_TX_SAT+0x34)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_7  (REG_TX_SAT+0x38)
#define TX_SAT_ADC_SAT_SHIFT_CTRL_LANE_8  (REG_TX_SAT+0x3c)
#define TX_SAT_DAC_SAT_COUNTERS_1         (REG_TX_SAT+0x40)
#define TX_SAT_DAC_SAT_COUNTERS_2         (REG_TX_SAT+0x44)
#define TX_SAT_DAC_SAT_COUNTERS_3         (REG_TX_SAT+0x48)
#define TX_SAT_DAC_SAT_COUNTERS_4         (REG_TX_SAT+0x4c)
#define TX_SAT_DAC_SAT_COUNTERS_5         (REG_TX_SAT+0x50)
#define TX_SAT_SAT_SELF_CLEARING          (REG_TX_SAT+0x54)
#define TX_SAT_ADC_SAT_LANE_DISABLE       (REG_TX_SAT+0x58)
#define TX_SAT_ADC_SAT_SHIFT              (REG_TX_SAT+0x5c)

#endif /* __TX_SAT_HXX__ */
